import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { PrismaClient } from '@prisma/client';
import { CollaborationStore, sqlDatabase } from '../src/lib/collaboration/store';
import { CollaborationService } from '../src/lib/collaboration/service';
import { createCollaborationHandlers } from '../src/lib/collaboration/http';

 test('original design: events alone, late Trace, repeated and cyclic edges, native evidence and owner isolation', async () => {
    const url = `file:${join(await mkdtemp(join(tmpdir(), 'collaboration-original-')), 'test.db')}`;
    const setup = spawnSync('node_modules/.bin/prisma', ['db', 'push', '--skip-generate'], { env: { ...process.env, DATABASE_URL: url, RUST_LOG: 'info' }, encoding: 'utf8' });
    assert.equal(setup.status, 0, setup.stderr);
    const client = new PrismaClient({ datasources: { db: { url } } });
    const store = new CollaborationStore(sqlDatabase(client));
    const service = new CollaborationService(store);
    const handlers = createCollaborationHandlers({ service, authenticate: async key => key === 'alice-key' ? 'alice' : key === 'bob-key' ? 'bob' : null });
    const request = (body?: unknown, key = 'alice-key') => new Request('http://localhost/api', { method: body ? 'POST' : 'GET', headers: { 'x-witty-api-key': key, 'content-type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
    const event = (id: string, from = 'A', to = 'B', extra = {}) => ({ collaborationId: 'demo', eventId: id, fromSessionId: from, toSessionId: to, description: '传递结果', ...extra });
    const addTrace = async (taskId: string, calls: unknown[], alias = taskId, user = 'alice') => {
        await client.session.create({ data: { taskId, user, interactions: JSON.stringify([{ role: 'assistant', agent: taskId, content: '执行原文', tool_calls: calls }]) } });
        await client.execution.create({ data: { id: `exec-${taskId}`, taskId, agentSessionId: alias, user, framework: 'opencode' } });
    };
    const call = (id: string, name: string, args: unknown, output?: unknown) => ({ id, function: { name, arguments: JSON.stringify(args) }, output });
    try {
        assert.equal((await handlers.report(request(event('first')))).status, 201);
        assert.equal((await handlers.report(request(event('first')))).status, 200);
        const empty = await service.graph('alice', 'demo');
        assert.equal(empty.nodes.length, 2); assert.equal(empty.events.length, 1);
        assert.ok(empty.nodes.every(node => node.traceResolution === 'unresolved'));
        assert.equal(empty.events[0].fromAnchor.status, 'not_provided');
        assert.equal(await client.session.count(), 0);
        assert.equal(await client.collaborationSessionBinding.count(), 0);
        assert.equal((await handlers.graph(request(undefined, 'bob-key'), 'demo')).status, 404);
        await handlers.report(request(event('second', 'A', 'B', { fromLocator: { recordType: 'tool', name: 'bash' } })));
        await handlers.report(request(event('cycle', 'B', 'A')));
        await handlers.report(request(event('self', 'A', 'A')));
        const firstPage = await service.graph('alice', 'demo', 0, 1);
        assert.equal(firstPage.total, 4); assert.equal(firstPage.events.length, 1); assert.equal(firstPage.nextOffset, 1);
        await addTrace('task-A', [call('bash-a', 'bash', { command: 'custom-worker' })], 'A');
        await addTrace('task-B', [call('read-b', 'read_file', { path: 'code.ts' })], 'B');
        const late = await service.graph('alice', 'demo');
        assert.equal(late.events.length, 4);
        assert.ok(late.nodes.every(node => node.traceResolution === 'resolved'));
        assert.equal(late.nodes.find(node => node.sessionId === 'A')?.traceSessionId, 'task-A');
        assert.equal(late.events.find(edge => edge.eventId === 'second')?.fromAnchor.status, 'candidate');
        assert.equal(await client.collaborationSessionBinding.count(), 0);
        await addTrace('root', [call('spawn-1', 'task', { session_id: 'middle' })]);
        await addTrace('middle', [call('spawn-2', 'task', { session_id: 'leaf' })]);
        await addTrace('leaf', [call('leaf-read', 'read_file', { path: 'file' })]);
        const native = await service.nativeGraph('alice', 'root');
        assert.equal(native.events.length, 0);
        assert.deepEqual(native.automaticEvents.map(edge => [edge.fromSessionId, edge.toSessionId]), [['root', 'middle'], ['middle', 'leaf']]);
        assert.equal(native.nodes.length, 3);
        assert.equal(await client.collaborationEvent.count(), 4);
        await assert.rejects(service.nativeGraph('bob', 'root'), /不存在或无权/);
        await handlers.report(request(event('native-report', 'root', 'middle')));
        const merged = await service.graph('alice', 'demo');
        assert.deepEqual(merged.events.find(edge => edge.eventId === 'native-report')?.sources, ['reported', 'trace']);
        assert.equal(merged.automaticEvents.filter(edge => edge.fromSessionId === 'root').length, 0);
        await addTrace('other-A', [], 'A');
        const ambiguous = await service.graph('alice', 'demo');
        assert.equal(ambiguous.nodes.find(node => node.sessionId === 'A')?.traceResolution, 'unresolved');
        assert.match(ambiguous.nodes.find(node => node.sessionId === 'A')?.message || '', /多个/);
        assert.equal(ambiguous.events.length, 5);
        assert.equal(await client.execution.count({ where: { isSubagent: true } }), 0);
    } finally { await client.$disconnect(); }
});
