' WorkBuddy Collector hidden-window launcher (template / reference).
'
' Running node.exe directly from Task Scheduler flashes a console window at logon.
' WScript.Shell.Run with window style 0 launches the collector fully hidden.
'
' It WAITS for the collector (bWaitOnReturn=True) and propagates its exit code via
' WScript.Quit, so Task Scheduler sees the task as Running while the collector lives
' and RestartOnFailure can revive it on crash.
'
' Note: the authoritative launcher is generated by workbuddy_setup.mjs at install time
' with the WorkBuddy.exe (or node) runtime path and collector.mjs path baked in, plus
' ELECTRON_RUN_AS_NODE=1. This template is a generic fallback: it finds node on PATH
' and takes collector.mjs next to itself.
Dim shell, fso, here, collector, code
Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
here = fso.GetParentFolderName(WScript.ScriptFullName)
collector = here & "\collector.mjs"
code = shell.Run("node.exe " & Chr(34) & collector & Chr(34), 0, True)
WScript.Quit(code)
