"""Per-run xiaoO config overlay: system config + FI hooker (do not strip RAS)."""

from __future__ import annotations

import json
import os
import re
import shutil
from pathlib import Path
from typing import Any


HOOKER_DIR = Path(__file__).resolve().parent / "hooker"
HOOK_SCRIPT = HOOKER_DIR / "fi_eval_hook.py"
PLUGIN_TEMPLATE = HOOKER_DIR / "plugin.json"
PLUGIN_CHAT_LLM_TEMPLATE = HOOKER_DIR / "plugin.chat-llm.json"

_GENERATED_MARKER = "Generated by agent-fault-injection XiaoOAdapter"


def default_user_config_path() -> Path:
    """Resolve the user's real xiaoO config (not a previous FI overlay)."""

    env = os.environ.get("XIAOO_CONFIG", "").strip()
    if env:
        candidate = Path(env).expanduser()
        if candidate.is_file() and not _looks_like_fi_overlay(candidate):
            return candidate
    return Path.home() / ".config" / "xiaoo" / "config.toml"


def _looks_like_fi_overlay(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:240]
    except OSError:
        return False
    if _GENERATED_MARKER in head:
        return True
    # Temp dirs from prepare_runtime_isolation.
    return "agent-fi-xiaoo-" in str(path)


def _parse_simple_toml_section(text: str, section: str) -> dict[str, Any]:
    """Minimal TOML section reader for [llm] / string-ish values (no deps)."""

    lines = text.splitlines()
    in_section = False
    values: dict[str, Any] = {}
    section_header = f"[{section}]"
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("[") and stripped.endswith("]"):
            in_section = stripped == section_header
            continue
        if not in_section:
            continue
        match = re.match(
            r'^([A-Za-z0-9_]+)\s*=\s*(.+)$',
            stripped,
        )
        if not match:
            continue
        key, raw = match.group(1), match.group(2).strip()
        if raw.startswith('"') and raw.endswith('"'):
            values[key] = raw[1:-1]
        elif raw.startswith("'") and raw.endswith("'"):
            values[key] = raw[1:-1]
        elif raw.lower() in {"true", "false"}:
            values[key] = raw.lower() == "true"
        else:
            try:
                values[key] = int(raw)
            except ValueError:
                try:
                    values[key] = float(raw)
                except ValueError:
                    values[key] = raw
    return values


def load_user_llm_config(path: Path | None = None) -> dict[str, Any]:
    config_path = path or default_user_config_path()
    if not config_path.is_file():
        return {}
    try:
        text = config_path.read_text(encoding="utf-8")
    except OSError:
        return {}
    return _parse_simple_toml_section(text, "llm")


def _toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _format_llm_toml(llm: dict[str, Any], model_override: str | None) -> str:
    lines = ["[llm]"]
    provider = llm.get("provider")
    model = model_override or llm.get("model")
    api_key_env = llm.get("api_key_env")
    api_base = llm.get("api_base")
    if isinstance(provider, str) and provider.strip():
        lines.append(f'provider = "{_toml_escape(provider.strip())}"')
    if isinstance(model, str) and model.strip():
        lines.append(f'model = "{_toml_escape(model.strip())}"')
    if isinstance(api_key_env, str) and api_key_env.strip():
        lines.append(f'api_key_env = "{_toml_escape(api_key_env.strip())}"')
    if isinstance(api_base, str) and api_base.strip():
        lines.append(f'api_base = "{_toml_escape(api_base.strip())}"')
    for key in ("max_tokens", "reasoning_effort"):
        value = llm.get(key)
        if isinstance(value, bool):
            continue
        if isinstance(value, (int, float)):
            lines.append(f"{key} = {value}")
        elif isinstance(value, str) and value.strip():
            lines.append(f'{key} = "{_toml_escape(value.strip())}"')
    return "\n".join(lines) + "\n"


def _format_plugins_toml(plugins: list[str]) -> str:
    if not plugins:
        return "plugins = []\n"
    lines = ["plugins = ["]
    for path in plugins:
        lines.append(f'  "{_toml_escape(path)}",')
    lines.append("]")
    return "\n".join(lines) + "\n"


def _extract_quoted_strings(blob: str) -> list[str]:
    return re.findall(r'"((?:\\.|[^"\\])*)"', blob)


def extract_hooker_plugins(text: str) -> list[str]:
    """Return plugin paths listed under the first ``[hooker]`` section."""

    match = re.search(
        r"(?ms)^\[hooker\]\s*(.*?)(?=^\[|\Z)",
        text,
    )
    if not match:
        return []
    body = match.group(1)
    plugins_match = re.search(
        r"(?ms)^\s*plugins\s*=\s*\[(.*?)\]",
        body,
    )
    if not plugins_match:
        return []
    return _extract_quoted_strings(plugins_match.group(1))


def _upsert_llm_model(text: str, model: str) -> str:
    """Set or insert ``model`` under ``[llm]`` without dropping sibling keys."""

    model_line = f'model = "{_toml_escape(model)}"'
    if re.search(r"(?m)^\[llm\]\s*$", text):
        if re.search(r"(?ms)^\[llm\]\s*.*?^\s*model\s*=", text):
            return re.sub(
                r"(?ms)(^\[llm\]\s*.*?^\s*)model\s*=\s*.*$",
                rf"\1{model_line}",
                text,
                count=1,
            )
        return re.sub(
            r"(?m)^(\[llm\]\s*)$",
            rf"\1\n{model_line}",
            text,
            count=1,
        )
    block = _format_llm_toml({}, model)
    if text and not text.endswith("\n"):
        text += "\n"
    return text + ("\n" if text else "") + block


def _upsert_hooker_plugins(text: str, plugins: list[str]) -> str:
    """Replace or append ``[hooker].plugins`` while keeping other hooker keys."""

    plugins_block = _format_plugins_toml(plugins).rstrip("\n")
    if re.search(r"(?m)^\[hooker\]\s*$", text):
        section = re.search(
            r"(?ms)^(\[hooker\]\s*)(.*?)(?=^\[|\Z)",
            text,
        )
        assert section is not None
        head, body = section.group(1), section.group(2)
        if re.search(r"(?ms)^\s*plugins\s*=\s*\[", body):
            body = re.sub(
                r"(?ms)^\s*plugins\s*=\s*\[.*?\]\s*",
                plugins_block + "\n",
                body,
                count=1,
            )
        else:
            body = plugins_block + "\n" + body
        return text[: section.start()] + head + body + text[section.end() :]

    block = (
        "[hooker]\n"
        'default = "All"\n'
        f"{plugins_block}\n"
        "enabled = []\n"
        "disabled = []\n"
    )
    if text and not text.endswith("\n"):
        text += "\n"
    return text + ("\n" if text.strip() else "") + block


def write_plugin_json(
    destination: Path,
    *,
    enable_chat_llm_hooks: bool = False,
) -> Path:
    """Copy plugin template with absolute hook script path."""

    if not HOOK_SCRIPT.is_file():
        raise FileNotFoundError(f"Missing xiaoO hook script: {HOOK_SCRIPT}")
    template = (
        PLUGIN_CHAT_LLM_TEMPLATE if enable_chat_llm_hooks else PLUGIN_TEMPLATE
    )
    if not template.is_file():
        raise FileNotFoundError(f"Missing plugin template: {template}")

    entries = json.loads(template.read_text(encoding="utf-8"))
    if not isinstance(entries, list):
        raise ValueError("plugin.json must be a JSON array")
    hook_cmd = f"python3 {HOOK_SCRIPT.resolve()}"
    rewritten: list[dict[str, Any]] = []
    for item in entries:
        if not isinstance(item, dict):
            continue
        copy = dict(item)
        copy["command"] = hook_cmd
        rewritten.append(copy)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(rewritten, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return destination


def write_run_config(
    *,
    destination: Path,
    plugin_json: Path,
    user_config_path: Path | None = None,
    model_override: str | None = None,
    llm: dict[str, Any] | None = None,
) -> Path:
    """Write XIAOO_CONFIG = system user config + FI hooker plugin.

    Preserves user ``[hooker].plugins`` (e.g. agent-insight RAS) and other
    sections; only overlays the FI plugin path and optional model override.
    Does not mutate the user's on-disk config.
    """

    source = user_config_path or default_user_config_path()
    user_text = ""
    if source.is_file():
        try:
            user_text = source.read_text(encoding="utf-8")
        except OSError:
            user_text = ""

    fi_plugin = str(plugin_json.resolve())
    plugins = [
        path
        for path in extract_hooker_plugins(user_text)
        if path != fi_plugin
    ]
    plugins.append(fi_plugin)

    if user_text.strip():
        text = user_text
        if model_override and model_override.strip():
            text = _upsert_llm_model(text, model_override.strip())
        text = _upsert_hooker_plugins(text, plugins)
    else:
        llm_data = dict(llm or {})
        text = _format_llm_toml(llm_data, model_override)
        text = _upsert_hooker_plugins(text, plugins)

    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = f"# {_GENERATED_MARKER} — do not edit by hand.\n{text}"
    if not payload.endswith("\n"):
        payload += "\n"
    destination.write_text(payload, encoding="utf-8")
    return destination


def prepare_overlay(
    *,
    overlay_root: Path,
    model_override: str | None = None,
    user_config_path: Path | None = None,
    enable_chat_llm_hooks: bool = False,
) -> tuple[Path, Path]:
    """Create FI plugin.json + merged config.toml under overlay_root.

    Returns ``(config_toml_path, plugin_json_path)``.
    """

    overlay_root.mkdir(parents=True, exist_ok=True)
    plugin_json = write_plugin_json(
        overlay_root / "plugin.json",
        enable_chat_llm_hooks=enable_chat_llm_hooks,
    )
    source = user_config_path or default_user_config_path()
    config_toml = write_run_config(
        destination=overlay_root / "config.toml",
        plugin_json=plugin_json,
        user_config_path=source,
        model_override=model_override,
        llm=load_user_llm_config(source) if not source.is_file() else None,
    )
    shutil.copy2(HOOK_SCRIPT, overlay_root / "fi_eval_hook.py")
    return config_toml, plugin_json
