import type { EvaluatorCard } from './custom-evaluator-model';

export const presetEvaluators: EvaluatorCard[] = [
  {
    id: 'preset-agent-task-completion',
    name: 'Agent 任务完成度',
    description: '评估 Agent 是否成功、完整地实现了用户目标，适合回归集和上线验收。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['任务完成', '内容质量'],
    scenarios: ['Agent通用评测'],
    runMode: 'LLM Judge',
    scoreRange: '0-1',
    popularity: 96,
    mappedMetrics: ['目标达成', '步骤完整', '答案可用'],
    status: 'ready',
    runtimeHref: '/eval/trajectory',
    runtimeNote: 'opencode-task-completion-evaluator.ts (single opencode agent)',
  },
  {
    id: 'preset-agent-trace-quality',
    name: 'Agent 轨迹质量',
    description: '评估 Agent 内部执行轨迹是否准确、稳定，关注规划、调用和中间结果。基于 opencode 单主评估器完成 completeness / tool-choice / attribution 判断，并结合规则冗余检测。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['轨迹质量'],
    scenarios: ['Agent通用评测', '轨迹评测'],
    runMode: 'Trace Judge (opencode)',
    scoreRange: '0-1',
    popularity: 91,
    mappedMetrics: ['轨迹准确性', '推理连续性', '异常处理'],
    status: 'ready',
    runtimeHref: '/eval/trajectory',
    runtimeNote: 'opencode-trajectory-evaluator.ts (single opencode agent)',
  },
  // ── 预置代码评估器（独立能力单元：零配置、不依赖参考数据、读执行过程 → 轨迹类）──
  // 实现：src/lib/evaluators/code-evaluators.ts；类目/前置条件声明：registry.ts
  {
    id: 'preset-code-tool-reliability',
    name: '工具调用可靠性',
    description: '按 trace 内工具调用错误率给分（硬错误口径：state / failures）；证据=失败工具与步骤清单（JSON）。',
    evaluatorType: 'Code',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['可靠性'],
    scenarios: ['工具链稳定性验收', '日常可靠性巡检'],
    runMode: 'Code (规则计算)',
    scoreRange: '0-100',
    popularity: 80,
    mappedMetrics: ['工具错误率'],
    status: 'ready',
    runtimeNote: 'code-evaluators.ts · evalToolReliability',
  },
  {
    id: 'preset-code-latency-budget',
    name: '时延预算',
    description: '端到端耗时对照预算阈值给分；证据=耗时与超支比例（JSON）。',
    evaluatorType: 'Code',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['性能'],
    scenarios: ['性能敏感场景的上线门禁'],
    runMode: 'Code (规则计算)',
    scoreRange: '0-100',
    popularity: 76,
    mappedMetrics: ['端到端时延'],
    status: 'ready',
    runtimeNote: 'code-evaluators.ts · evalLatencyBudget',
  },
  {
    id: 'preset-code-cost-budget',
    name: '成本预算',
    description: '按模型单价加权的 trace 成本对照预算给分；证据=成本构成（JSON）。单价缺失时诚实不记分。',
    evaluatorType: 'Code',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['成本'],
    scenarios: ['控本：模型 / 编排调整后确认单任务成本不回涨'],
    runMode: 'Code (规则计算)',
    scoreRange: '0-100',
    popularity: 74,
    mappedMetrics: ['单任务成本'],
    status: 'ready',
    runtimeNote: 'code-evaluators.ts · evalCostBudget',
  },
  {
    id: 'preset-code-redundancy-loop',
    name: '冗余循环检测',
    description: '检测重复工具调用与循环执行模式，按冗余步数占比给分；证据=重复调用对与高频调用清单（JSON）。',
    evaluatorType: 'Code',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['轨迹质量'],
    scenarios: ['定位 Agent 空转', '常与轨迹质量搭配'],
    runMode: 'Code (规则计算)',
    scoreRange: '0-100',
    popularity: 72,
    mappedMetrics: ['冗余度'],
    status: 'ready',
    runtimeNote: 'code-evaluators.ts · evalRedundancyLoop',
  },
  {
    id: 'preset-code-token-efficiency',
    name: 'Token 效率',
    description: '单位任务 Token 对照基线给分，识别上下文膨胀与超长单次调用；证据=用量明细（JSON）。',
    evaluatorType: 'Code',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['成本', '效率'],
    scenarios: ['上下文膨胀排查'],
    runMode: 'Code (规则计算)',
    scoreRange: '0-100',
    popularity: 70,
    mappedMetrics: ['单位任务 Token'],
    status: 'ready',
    runtimeNote: 'code-evaluators.ts · evalTokenEfficiency',
  },
  // ── 结果评测评估器（抽取自「可靠性与性能」的结果评测分析能力，与其共用同一 canonical 实现）──
  // 实现：result-preset-evaluators.ts（复用 result-quality-evaluator 的 runSingleResultMetric）
  {
    id: 'preset-result-accuracy',
    name: '结果准确性',
    description: '对照参考答案，逐关键观点判定 covered/partial/wrong/not_mentioned + 证据；与可靠性页同口径。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['结果准确'],
    scenarios: ['有标准答案的结果验收'],
    runMode: 'LLM Judge (直连 · GT rubric)',
    scoreRange: '0-100',
    popularity: 90,
    mappedMetrics: ['关键观点覆盖'],
    status: 'ready',
    runtimeNote: 'result-preset-evaluators.ts · accuracy',
  },
  {
    id: 'preset-result-answer',
    name: '答案质量',
    description: '评估最终答案的相关性 / 完整性 / 连贯性三子维度；不依赖参考答案。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['内容质量'],
    scenarios: ['开放式回答质量评估'],
    runMode: 'LLM Judge (直连 · self rubric)',
    scoreRange: '0-100',
    popularity: 84,
    mappedMetrics: ['相关性', '完整性', '连贯性'],
    status: 'ready',
    runtimeNote: 'result-preset-evaluators.ts · answer-quality',
  },
  {
    id: 'preset-result-faithfulness',
    name: '忠实度',
    description: '检测答案主张是否有执行轨迹证据支撑（幻觉检测）；证据=逐主张裁决与引用。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['可信度'],
    scenarios: ['幻觉排查', '证据支撑核验'],
    runMode: 'LLM Judge (直连 · grounding)',
    scoreRange: '0-100',
    popularity: 82,
    mappedMetrics: ['主张支撑率'],
    status: 'ready',
    runtimeNote: 'result-preset-evaluators.ts · faithfulness',
  },
  {
    id: 'preset-result-instruction',
    name: '指令遵循',
    description: '抽取任务/系统指令约束并逐条判定是否遵守（met/not_met）；不依赖参考答案。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['合规'],
    scenarios: ['约束遵循核验'],
    runMode: 'LLM Judge (直连 · self rubric)',
    scoreRange: '0-100',
    popularity: 80,
    mappedMetrics: ['约束满足率'],
    status: 'ready',
    runtimeNote: 'result-preset-evaluators.ts · instruction-adherence',
  },
];
