/**
 * 预置评估器元数据目录：定义评估器列表页和实验选择步骤使用的稳定 ID、名称、摘要、
 * 评估目标、适用场景、分数范围及运行实现提示。
 *
 * 本文件只声明产品层元数据，不执行评估。详情页结合本文件与 registry.ts 派生展示内容；
 * 实际 Prompt、轨迹统计和确定性计分位于 src/lib/engine/experiment/。
 */
import type { EvaluatorCard } from './custom-evaluator-model';
import { SKILL_TRIGGER_ANALYZER_EVALUATOR_ID } from '@/lib/skill-workbench/trigger-evaluator';

/**
 * 「用例分析」「批量测试」里默认勾选的评估器。
 *
 * **必须是显式列表，不要改回从 `status === 'ready'` 派生。** 派生的话，每新增一个预置
 * 评估器，「用户什么都没点就点评测」的默认行为就会多跑一个 LLM judge——而通用 judge
 * 每调一次会起一个临时 opencode server（`judge-llm.ts`），后台并发上限只有 5。
 * 参见 `eval-run-guards.ts` 记录的那次「并行跑多个评测任务 → next-server 堆 OOM」事故。
 *
 * 下拉框仍然列出全部 ready 的评估器，用户可以自行加勾——这里只管默认值。
 */
export const DEFAULT_SELECTED_PRESET_IDS: readonly string[] = [
  'preset-agent-task-completion',
  'preset-agent-trace-quality',
];

export const presetEvaluators: EvaluatorCard[] = [
  {
    id: SKILL_TRIGGER_ANALYZER_EVALUATOR_ID,
    name: 'skill-trigger-analyzer',
    description: '逐条比较数据集应触发标注与当前 Skill 的真实路由结果，每条 Case 只输出一个「触发准确率」评分点。',
    evaluatorType: 'Code',
    source: 'preset',
    category: 'res',
    targetTypes: ['路由'],
    objectives: ['触发准确率'],
    scenarios: ['Skill 触发分析'],
    runMode: '确定性路由判定',
    scoreRange: '0-100',
    popularity: 100,
    mappedMetrics: ['触发准确率'],
    status: 'ready',
    runtimeNote: '实时路由 / 已有 Trace · should_trigger === skill_triggered',
  },
  {
    id: 'preset-agent-task-completion',
    name: 'Agent 任务完成度',
    description: '评估 Agent 是否成功、完整地实现了用户目标，适合回归集和上线验收。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['任务完成', '内容质量'],
    scenarios: ['Agent通用评测'],
    runMode: 'LLM Judge',
    scoreRange: '0-100',
    popularity: 96,
    mappedMetrics: ['目标达成', '步骤完整', '答案可用'],
    status: 'ready',
    runtimeHref: '/eval/trajectory',
    runtimeNote: 'opencode-task-completion-evaluator.ts (single opencode agent)',
  },
  {
    id: 'preset-agent-trace-quality',
    name: 'Agent 轨迹质量',
    description: '评估 Agent 内部执行轨迹是否准确、稳定，关注规划、调用和中间结果。基于 opencode 单主评估器完成 completeness / tool-choice / attribution 判断，并结合规则冗余检测。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['轨迹质量'],
    scenarios: ['Agent通用评测', '轨迹评测'],
    runMode: 'Trace Judge (opencode)',
    scoreRange: '0-100',
    popularity: 91,
    mappedMetrics: ['轨迹准确性', '推理连续性', '异常处理'],
    status: 'ready',
    runtimeHref: '/eval/trajectory',
    runtimeNote: 'opencode-trajectory-evaluator.ts (single opencode agent)',
  },
  // ── 结果评测评估器（评测中心独立能力，共用同一 canonical 实现）──
  // 实现：result-preset-evaluators.ts（复用 result-metric-evaluator 的 runSingleResultMetric）
  {
    id: 'preset-result-accuracy',
    name: '结果准确性',
    description: '对照参考答案，逐关键观点判定 covered/partial/wrong/not_mentioned + 证据；与可靠性页同口径。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['结果准确'],
    scenarios: ['有标准答案的结果验收'],
    runMode: 'LLM Judge (直连 · GT rubric)',
    scoreRange: '0-100',
    popularity: 90,
    mappedMetrics: ['关键观点覆盖'],
    status: 'ready',
    runtimeNote: 'result-preset-evaluators.ts · accuracy',
  },
  {
    id: 'preset-result-answer',
    name: '答案质量',
    description: '评估最终答案的相关性 / 完整性 / 连贯性三子维度；不依赖参考答案。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['内容质量'],
    scenarios: ['开放式回答质量评估'],
    runMode: 'LLM Judge (直连 · self rubric)',
    scoreRange: '0-100',
    popularity: 84,
    mappedMetrics: ['相关性', '完整性', '连贯性'],
    status: 'ready',
    runtimeNote: 'result-preset-evaluators.ts · answer-quality',
  },
  {
    id: 'preset-result-faithfulness',
    name: '忠实度',
    description: '检测答案主张是否有执行轨迹证据支撑（幻觉检测）；证据=逐主张裁决与引用。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['可信度'],
    scenarios: ['幻觉排查', '证据支撑核验'],
    runMode: 'LLM Judge (直连 · grounding)',
    scoreRange: '0-100',
    popularity: 82,
    mappedMetrics: ['主张支撑率'],
    status: 'ready',
    runtimeNote: 'result-preset-evaluators.ts · faithfulness',
  },
  {
    id: 'preset-result-instruction',
    name: '指令遵循',
    description: '抽取任务/系统指令约束并逐条判定是否遵守（met/not_met）；不依赖参考答案。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['合规'],
    scenarios: ['约束遵循核验'],
    runMode: 'LLM Judge (直连 · self rubric)',
    scoreRange: '0-100',
    popularity: 80,
    mappedMetrics: ['约束满足率'],
    status: 'ready',
    runtimeNote: 'result-preset-evaluators.ts · instruction-adherence',
  },
  // ── 内容质量评估器 ──
  // 实现：content-preset-evaluators.ts
  {
    id: 'preset-content-insensitivity',
    name: '不敏感性评估',
    description: '从人群身份、地域、职业阶层、年龄外貌、文化宗教五个维度评估 Agent 输出文本是否包含不敏感的、冒犯性的或歧视性内容（性别相关问题由性别歧视性评估器专项检测）。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['安全合规', '内容质量'],
    scenarios: ['内容安全审查', 'Agent通用评测'],
    runMode: 'LLM Judge (直连)',
    scoreRange: '0-100',
    popularity: 78,
    mappedMetrics: ['身份敏感', '地域敏感', '职业阶层敏感', '年龄外貌敏感', '文化宗教敏感'],
    status: 'ready',
    runtimeNote: 'content-preset-evaluators.ts · insensitivity',
  },
  {
    id: 'preset-content-controversy',
    name: '争议性评估',
    description: '从绝对化判断、争议性比较、未经限定概括三个维度评估 Agent 输出文本的争议性表述方式（聚焦语言学形式，不评估内容主题）。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['安全合规', '内容质量'],
    scenarios: ['内容安全审查', 'Agent通用评测'],
    runMode: 'LLM Judge (直连)',
    scoreRange: '0-100',
    popularity: 76,
    mappedMetrics: ['绝对化判断', '争议性比较', '未经限定概括'],
    status: 'ready',
    runtimeNote: 'content-preset-evaluators.ts · controversy',
  },
  {
    id: 'preset-content-gender-discrimination',
    name: '性别歧视性评估',
    description: '从显性贬低、能力否定、刻板印象、排斥语言、物化、双重标准、角色固着七个维度评估 Agent 输出文本的性别平等水平。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['安全合规', '内容质量'],
    scenarios: ['内容公平性审查', 'Agent通用评测'],
    runMode: 'LLM Judge (直连)',
    scoreRange: '0-100',
    popularity: 74,
    mappedMetrics: ['显性贬低', '能力否定', '刻板印象', '排斥语言', '物化', '双重标准', '角色固着'],
    status: 'ready',
    runtimeNote: 'content-preset-evaluators.ts · gender-discrimination',
  },
  {
    id: 'preset-creativity-expression',
    name: '创造性评估',
    description: '从新颖性、视角独特性、表达非模板化、构思差异度、文采与修辞五个维度评估 Agent 生成文本的创造性水平。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['内容质量'],
    scenarios: ['创意质量评估', 'Agent通用评测'],
    runMode: 'LLM Judge (直连)',
    scoreRange: '0-100',
    popularity: 72,
    mappedMetrics: ['新颖性', '视角独特性', '非模板化', '构思差异度', '文采修辞'],
    status: 'ready',
    runtimeNote: 'creativity-preset-evaluators.ts · creativity',
  },
  {
    id: 'preset-text-ai-flavor',
    name: '文本 AI 味检查',
    description: '从模板化开篇、模板化结尾、机械连接词、泛化人物名称、空洞总结和过度礼貌六个维度评估 Agent 输出的自然度。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['内容质量'],
    scenarios: ['客服对话', '内容创作'],
    runMode: 'LLM Judge (离散 rubric)',
    scoreRange: '0-100',
    popularity: 75,
    mappedMetrics: ['模板化表达', '机械连接', '空洞总结', '过度礼貌'],
    status: 'ready',
    runtimeNote: 'text-preset-evaluators.ts · ai-flavor',
  },
  {
    id: 'preset-text-format',
    name: '文本格式规范性',
    description: '检查序号、引用、列表层级、标点、排版、表格及 URL/日期等特殊格式的一致性与可渲染性。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['内容质量'],
    scenarios: ['报告生成', '内容创作'],
    runMode: 'LLM Judge (离散 rubric)',
    scoreRange: '0-100',
    popularity: 73,
    mappedMetrics: ['编号连续', '引用规范', '排版一致', '表格格式'],
    status: 'ready',
    runtimeNote: 'text-preset-evaluators.ts · format',
  },
  {
    id: 'preset-text-language-consistency',
    name: '文本语种一致性',
    description: '比较用户输入与 Agent 回复的主语言，识别不必要的语言混杂，并豁免技术术语、品牌名、翻译和原文引用。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['内容质量'],
    scenarios: ['双语对话', 'AI翻译'],
    runMode: 'LLM Judge (离散 rubric)',
    scoreRange: '0-100',
    popularity: 74,
    mappedMetrics: ['主语言匹配', '非必要混杂', '语种切换合理性', '双语处理'],
    status: 'ready',
    runtimeNote: 'text-preset-evaluators.ts · language-consistency',
  },
  {
    id: 'preset-text-conciseness',
    name: '文本简洁性',
    description: '从表达效率、套话精简、主需求聚焦和信息完整四个维度评估回答是否精炼且不遗漏必要信息。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['内容质量'],
    scenarios: ['问答助手', '摘要生成'],
    runMode: 'LLM Judge (离散 rubric)',
    scoreRange: '0-100',
    popularity: 76,
    mappedMetrics: ['表达效率', '套话精简', '需求聚焦', '信息完整'],
    status: 'ready',
    runtimeNote: 'text-preset-evaluators.ts · conciseness',
  },
  {
    id: 'preset-safety-maliciousness',
    name: '恶意性',
    description: '从攻击、威胁、伤害诱导、欺诈、自伤诱导、霸凌和破坏性建议七个维度检测 Agent 输出中的恶意风险。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['安全合规'],
    scenarios: ['恶意内容检测'],
    runMode: 'LLM Judge (离散裁决)',
    scoreRange: '0-100',
    popularity: 88,
    mappedMetrics: ['人身攻击与侮辱', '威胁与恐吓', '诱导伤害', '恶意操纵与欺诈', '自残与自伤诱导', '骚扰与霸凌', '破坏性建议'],
    status: 'ready',
    runtimeNote: 'safety-preset-evaluators.ts · maliciousness',
  },
  {
    id: 'preset-safety-harmfulness',
    name: '有害性',
    description: '从冒犯、客观伤害、歧视、危险建议、不当引导和情绪伤害六个维度检测 Agent 输出的客观有害风险。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['安全合规'],
    scenarios: ['有害内容检测'],
    runMode: 'LLM Judge (离散裁决)',
    scoreRange: '0-100',
    popularity: 87,
    mappedMetrics: ['冒犯性', '伤害性', '歧视性', '危险建议', '不当引导', '情绪伤害'],
    status: 'ready',
    runtimeNote: 'safety-preset-evaluators.ts · harmfulness',
  },
  {
    id: 'preset-safety-criminality',
    name: '犯罪性',
    description: '检测 Agent 输出是否描述、鼓励、指导、便利或不当合理化违法犯罪行为，并识别可执行犯罪方法。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['安全合规'],
    scenarios: ['犯罪引导检测'],
    runMode: 'LLM Judge (离散裁决)',
    scoreRange: '0-100',
    popularity: 86,
    mappedMetrics: ['犯罪描述', '犯罪鼓励', '犯罪指导', '犯罪便利', '犯罪合理化与淡化'],
    status: 'ready',
    runtimeNote: 'safety-preset-evaluators.ts · criminality',
  },
  {
    id: 'preset-safety-refusal',
    name: '文本-拒答检测',
    description: '结合用户问题和 Agent 回复，检测该拒不拒、拒答是否充分、是否过度拒答以及是否提供安全替代。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['安全合规'],
    scenarios: ['拒答质量检测'],
    runMode: 'LLM Judge (离散裁决)',
    scoreRange: '0-100',
    popularity: 89,
    mappedMetrics: ['触发条件判断', '拒答正确性', '拒答充分性', '过度拒答检测', '替代方案提供'],
    status: 'ready',
    runtimeNote: 'safety-preset-evaluators.ts · text-refusal',
  },
  {
    id: 'preset-depth-result',
    name: '回答深度性',
    description: '按问题所需深度评估因果、结构、权衡、背景与洞察；不重复评价答案完整性和连贯性。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['内容质量'],
    scenarios: ['开放式回答质量评估', '分析深度评估'],
    runMode: 'LLM Judge (离散 rubric)',
    scoreRange: '0-100',
    popularity: 79,
    mappedMetrics: ['因果深度', '结构化推理', '多视角权衡', '背景语境', '洞察升华'],
    status: 'ready',
    runtimeNote: 'depth-preset-evaluators.ts',
  },
  {
    id: 'preset-agent-tool-utilization',
    name: '轨迹工具利用率',
    description: '结合显式 Tool/Skill 目录，以必要能力覆盖率、调用匹配率和调用节制率计算百分制；闲置原因作为评估依据展示。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['轨迹质量', '执行效率'],
    scenarios: ['Agent通用评测', '轨迹评测'],
    runMode: 'Trace Judge（语义判断 + 比例聚合）',
    scoreRange: '0-100',
    popularity: 78,
    mappedMetrics: ['必要能力覆盖率', '调用匹配率', '调用节制率'],
    status: 'ready',
    runtimeNote: 'agent-tool-utilization-evaluator.ts',
  },
  {
    id: 'preset-agent-tool-selection',
    name: 'Agent 工具选择合理性',
    description: '逐步检查 Tool/Skill 必要性、任务匹配、参数来源、结果利用与依赖顺序，问题定位到能力和步骤。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['轨迹质量', '工具调用质量'],
    scenarios: ['Agent通用评测', '轨迹评测'],
    runMode: 'Trace Judge (规则 + 离散 rubric)',
    scoreRange: '0-100',
    popularity: 77,
    mappedMetrics: ['工具必要性', '工具匹配', '参数合理性', '结果利用', '调用顺序'],
    status: 'ready',
    runtimeNote: 'agent-tool-selection-evaluator.ts',
  },
  {
    id: 'preset-ras-reliability-detection-recovery',
    name: 'Agent RAS 可靠性故障检测恢复评估器',
    description: '先确认预期故障真实发生，再基于 Trace 与 RAS 故障事件评估故障检测、触发处置和故障消解能力；未确认故障时不评分。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['可靠性'],
    scenarios: ['可靠性评测', '故障恢复'],
    runMode: 'Trace + Fault Events',
    scoreRange: '0-100',
    popularity: 70,
    mappedMetrics: ['故障检测', '触发处置', '故障消解'],
    status: 'ready',
    runtimeNote: 'ras-reliability-evaluator.ts（invokeSpecializedJudge / 模型注册活跃配置）',
  },
  {
    id: 'preset-agent-tool-success-rate',
    name: '工具调用成功率',
    description: '评估 Agent 执行过程中工具调用的成功率，从整体成功率、按工具聚合失败率、错误模式分析和失败影响评估四个维度进行全面分析。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['轨迹质量', '工具调用质量'],
    scenarios: ['Agent通用评测', '轨迹评测'],
    runMode: 'LLM Judge',
    scoreRange: '0-100',
    popularity: 70,
    mappedMetrics: ['整体成功率', '工具失败率', '错误模式', '失败影响'],
    status: 'ready',
    runtimeNote: 'agent-tool-success-rate-evaluator.ts',
  },
  {
    id: 'preset-task-completion-no-ref',
    name: '任务完成度（无标准答案）',
    description: '在无标准答案的情况下评估 Agent 任务的完成度，采用需求推断、逐条对齐和置信度标记的三阶段方法，适用于开放式任务和缺少参考答案的场景。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['结果'],
    objectives: ['任务完成', '内容质量'],
    scenarios: ['Agent通用评测'],
    runMode: 'LLM Judge',
    scoreRange: '0-100',
    popularity: 65,
    mappedMetrics: ['显式需求完成', '隐含约束满足', '信息充分性'],
    status: 'ready',
    runtimeNote: 'task-completion-preset-evaluators.ts',
  },
];

/** 仅供历史实验解析名称；不进入评估器目录和新建实验可选列表。 */
export const legacyPresetEvaluators: EvaluatorCard[] = [
  {
    id: 'preset-ras-reliability-fault-injection',
    name: 'Agent RAS 可靠性故障注入评估器',
    description: '已停用的故障发生评估器，仅用于兼容历史实验与结果。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['可靠性'],
    scenarios: ['历史可靠性评测'],
    runMode: 'Trace + Fault Events',
    scoreRange: '0-100',
    popularity: 0,
    mappedMetrics: ['故障发生'],
    status: 'draft',
    runtimeNote: 'ras-reliability-evaluator.ts（历史兼容）',
  },
  {
    id: 'preset-ras-reliability',
    name: 'Agent RAS 可靠性评估器',
    description: '旧五维可靠性评估器，仅用于兼容历史实验与结果。',
    evaluatorType: 'LLM',
    source: 'preset',
    targetTypes: ['轨迹'],
    objectives: ['可靠性'],
    scenarios: ['历史可靠性评测'],
    runMode: 'Trace + Fault Events',
    scoreRange: '0-100',
    popularity: 0,
    mappedMetrics: ['故障发生', '故障检测', '触发处置', '故障消解', '最终任务结果'],
    status: 'draft',
    runtimeNote: 'ras-reliability-evaluator.ts（历史兼容）',
  },
];
