import { NextResponse } from 'next/server';

// 安装页可预选的框架。value 会被拼进生成脚本，所以只接受白名单内的值——
// 不能把 query 参数原样带进 shell/PowerShell 字符串。
const FRAMEWORKS: { value: string; label: string }[] = [
    { value: 'opencode', label: 'OpenCode' },
    { value: 'openclaw', label: 'OpenClaw' },
    { value: 'claude', label: 'Claude Code' },
    { value: 'codeagent', label: 'CodeAgent' },
    { value: 'hermes', label: 'Hermes' },
    { value: 'jiuwen', label: 'JiuwenSwarm' },
    { value: 'trae', label: 'Trae IDE' },
];

function parseFrameworks(raw: string | null): { value: string; label: string }[] {
    if (!raw) return [];
    const wanted = new Set(raw.split(',').map(s => s.trim().toLowerCase()).filter(Boolean));
    return FRAMEWORKS.filter(f => wanted.has(f.value));
}

function detectPlatform(request: Request): 'windows' | 'unix' {
    const userAgent = request.headers.get('user-agent') || '';
    const platformHeader = request.headers.get('x-platform') || '';
    
    if (platformHeader) {
        return platformHeader.toLowerCase() === 'windows' ? 'windows' : 'unix';
    }
    
    if (userAgent.toLowerCase().includes('windows')) {
        return 'windows';
    }
    
    return 'unix';
}

function bashDoubleQuoted(value: string): string {
    return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$').replace(/`/g, '\\`');
}

function powerShellDoubleQuoted(value: string): string {
    return value.replace(/`/g, '``').replace(/"/g, '`"').replace(/\$/g, '`$');
}

function generateBashScript(host: string, baseUrl: string, apiKey: string, preselected: { value: string; label: string }[]): string {
    const lines = [
        '#!/bin/bash',
        '# =============================================================================',
        '# Agent-insight One-Click Setup',
        '# =============================================================================',
        '',
        'AGENT_INSIGHT_HOST="' + bashDoubleQuoted(host) + '"',
        'AGENT_INSIGHT_BASE_URL="' + bashDoubleQuoted(baseUrl) + '"',
        'AGENT_INSIGHT_SETUP_API_KEY="' + bashDoubleQuoted(apiKey) + '"',
        'OPENCODE_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/opencode"',
        '',
        'echo "🚀 Fetching Agent-insight telemetry components from $AGENT_INSIGHT_BASE_URL..."',
        '',
        '# 0. Check Node.js version',
        'if ! command -v node &> /dev/null; then',
        '    echo "❌ Error: Node.js is not installed."',
        '    echo "   Agent-insight requires Node.js 20 or higher."',
        '    echo "   Please install Node.js: https://nodejs.org/"',
        '    exit 1',
        'fi',
        '',
        'NODE_VERSION=$(node -v 2>/dev/null | sed "s/v//")',
        'NODE_MAJOR=$(echo "$NODE_VERSION" | cut -d. -f1)',
        'if [ "$NODE_MAJOR" -lt 20 ]; then',
        '    echo "❌ Error: Node.js version $NODE_VERSION is not supported."',
        '    echo "   Agent-insight requires Node.js 20 or higher."',
        '    echo "   Please upgrade your Node.js version: https://nodejs.org/"',
        '    exit 1',
        'fi',
        'echo "✅ Node.js version: $NODE_VERSION"',
        '',
        '# 1. Setup Directories',
        'mkdir -p "$HOME/.agent-insight"',
        'mkdir -p "$HOME/.agent-insight/logs"',
        'mkdir -p "$HOME/.opencode/plugins"',
        'mkdir -p "$OPENCODE_CONFIG_DIR/plugins"',
        'mkdir -p "$HOME/.opencode/skills"',
        'mkdir -p "$HOME/.claude/projects"',
        'mkdir -p ".opencode/skills"',
        'mkdir -p "$HOME/.agent-insight/example"',
        'echo "📂 Created necessary directories"',
        '',
        '# 1b. Download built-in example messages log (for the bundled "messages 日志分析" dataset / demo traces)',
        'if curl -sSf "$AGENT_INSIGHT_BASE_URL/api/setup/example-messages" -o "$HOME/.agent-insight/example/messages"; then',
        '    echo "📄 Example log ready at $HOME/.agent-insight/example/messages"',
        'else',
        '    echo "⚠️  Skipped example messages log download (non-fatal)"',
        'fi',
        '',
        // 安装页勾选了框架时，SELECTED_FRAMEWORKS 直接写死，跳过下面整段交互式选择——
        // 那段要 npm install inquirer/tsx + npx，内网/离线环境访问不到 registry 就卡死在这里。
        '# 2. Framework selection',
        'SELECTED_FRAMEWORKS="' + preselected.map(f => f.value).join(',') + '"',
        'if [ -n "$SELECTED_FRAMEWORKS" ]; then',
        '    echo ""',
        '    echo "✅ 将安装以下组件: ' + bashDoubleQuoted(preselected.map(f => f.label).join('、')) + '"',
        '    echo ""',
        'else',
        '# 2b. Interactive Framework Selection with inquirer',
        'echo ""',
        '',
        'SELECTOR_SCRIPT="$HOME/.agent-insight/framework_selector.mjs"',
        'SELECTOR_RESULT="$HOME/.agent-insight/.selector_result"',
        '',
        '# Install inquirer and tsx if not already installed',
        'cd "$HOME/.agent-insight"',
        'if [ ! -f "package.json" ]; then',
        '    echo \'{"name": "agent-insight-setup", "version": "1.0.0", "type": "module", "dependencies": {}}\' > package.json',
        'fi',
        'if [ ! -d "node_modules/inquirer" ] || [ ! -d "node_modules/tsx" ]; then',
        '    echo "📦 Installing dependencies for interactive selection..."',
        '    npm install inquirer tsx --save 2>/dev/null',
        'fi',
        '',
        'cat > "$SELECTOR_SCRIPT" << \'SELECTOR_EOF\'',
        'import inquirer from \'inquirer\';',
        'import fs from \'fs\';',
        '',
        'const frameworks = [',
        '    { name: \'OpenCode\', value: \'opencode\' },',
        '    { name: \'OpenClaw\', value: \'openclaw\' },',
        '    { name: \'Claude Code\', value: \'claude\' },',
        '    { name: \'CodeAgent\', value: \'codeagent\' },',
        '    { name: \'Hermes\', value: \'hermes\' },',
'    { name: \'JiuwenSwarm\', value: \'jiuwen\' },',
'    { name: \'Trae IDE\', value: \'trae\' }',
        '];',
        '',
        'async function select() {',
        '    console.log(\'\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'╔══════════════════════════════════════════════════════════╗\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'║                                                          ║\');',
        '    console.log(\'\\x1b[1m\\x1b[36m%s\\x1b[0m\', \'║                 ✨ Agent-insight ✨                      ║\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'║                                                          ║\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'╚══════════════════════════════════════════════════════════╝\');',
        '    console.log(\'\');',
        '    console.log(\'\\x1b[90m%s\\x1b[0m\', \'  提示: ↑↓ 移动  |  空格 选择  |  a 全选  |  i 反选  |  Enter 确认\');',
        '    console.log(\'\');',
        '',
        '    const answers = await inquirer.prompt([',
        '        {',
        '            type: \'checkbox\',',
        '            name: \'frameworks\',',
        '            message: \'集成到：\',',
        '            choices: frameworks,',
        '            default: [\'opencode\'],',
        '            pageSize: 10,',
        '            loop: false',
        '        }',
        '    ]);',
        '',
        '    const selected = answers.frameworks;',
        '    ',
        '    if (selected.length > 0) {',
        '        console.log(\'\');',
        '        console.log(\'\\x1b[32m%s\\x1b[0m\', \'✅ 将安装以下组件:\');',
        '        selected.forEach(fw => {',
        '            const name = frameworks.find(f => f.value === fw)?.name || fw;',
        '            console.log(\'\\x1b[32m%s\\x1b[0m\', \'   • \' + name);',
        '        });',
        '        console.log(\'\');',
        '    } else {',
        '        console.log(\'\');',
        '        console.log(\'\\x1b[33m%s\\x1b[0m\', \'⚠️  未选择任何组件，将不进行安装。\');',
        '        console.log(\'\');',
        '    }',
        '',
        '    const resultFile = process.env.SELECTOR_RESULT_FILE || process.env.HOME + \'/.agent-insight/.selector_result\';',
        '    fs.writeFileSync(resultFile, selected.join(\',\'));',
        '}',
        '',
        'select().catch(err => {',
        '    console.error(\'Error:\', err);',
        '    process.exit(1);',
        '});',
        'SELECTOR_EOF',
        '',
        '# Run the selector interactively from /dev/tty',
        'export SELECTOR_RESULT_FILE="$SELECTOR_RESULT"',
        'cd "$HOME/.agent-insight" && npx -y tsx "$SELECTOR_SCRIPT" < /dev/tty',
        '',
        '# Read the selection result from file',
        'if [ -f "$SELECTOR_RESULT" ]; then',
        '    SELECTED_FRAMEWORKS=$(cat "$SELECTOR_RESULT")',
        '    rm -f "$SELECTOR_RESULT"',
        'else',
        '    SELECTED_FRAMEWORKS=""',
        'fi',
        'fi',
        '',
        '# Set installation flags based on selection',
        'INSTALL_OPENCODE=false',
        'INSTALL_CLAUDE=false',
        'INSTALL_OPENCLAW=false',
        'INSTALL_CODEAGENT=false',
        'INSTALL_HERMES=false',
        'INSTALL_JIUWEN=false',
        'INSTALL_TRAE=false',
        '',
        'if [[ "$SELECTED_FRAMEWORKS" == *"opencode"* ]]; then',
        '    INSTALL_OPENCODE=true',
        'fi',
        'if [[ "$SELECTED_FRAMEWORKS" == *"claude"* ]]; then',
        '    INSTALL_CLAUDE=true',
        'fi',
        'if [[ "$SELECTED_FRAMEWORKS" == *"openclaw"* ]]; then',
        '    INSTALL_OPENCLAW=true',
        'fi',
        'if [[ "$SELECTED_FRAMEWORKS" == *"codeagent"* ]]; then',
        '    INSTALL_CODEAGENT=true',
        'fi',
        'if [[ "$SELECTED_FRAMEWORKS" == *"hermes"* ]]; then',
        '    INSTALL_HERMES=true',
        'fi',
        'if [[ "$SELECTED_FRAMEWORKS" == *"jiuwen"* ]]; then',
        '    INSTALL_JIUWEN=true',
        'fi',
        'if [[ "$SELECTED_FRAMEWORKS" == *"trae"* ]]; then',
        '    INSTALL_TRAE=true',
        'fi',
        '',
        '# Exit if nothing selected',
        'if [ "$INSTALL_OPENCODE" = "false" ] && [ "$INSTALL_CLAUDE" = "false" ] && [ "$INSTALL_OPENCLAW" = "false" ] && [ "$INSTALL_CODEAGENT" = "false" ] && [ "$INSTALL_HERMES" = "false" ] && [ "$INSTALL_JIUWEN" = "false" ] && [ "$INSTALL_TRAE" = "false" ]; then',
        '    echo "⚠️  未选择任何框架组件，将跳过插件安装。"',
        '    echo "   继续执行配置步骤..."',
        '    echo ""',
        'fi',
        '',
        '# 3. Download Components',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then',
        '    echo "⏬ Downloading OpenCode Plugin..."',
        '    rm -f "$OPENCODE_CONFIG_DIR/plugins/Skill-Insight.ts" "$OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.ts" 2>/dev/null || true',
        '    rm -f "$HOME/.opencode/plugins/Skill-Insight.ts" "$HOME/.opencode/plugins/Witty-Skill-Insight.ts" "$HOME/.opencode/plugins/Witty-Skill-Insight.tui.tsx" 2>/dev/null || true',
        '    curl -sSf "$AGENT_INSIGHT_BASE_URL/api/setup/opencode" -o "$OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.ts"',
        '    echo "⏬ Downloading OpenCode Uploader..."',
        '    curl -sSf "$AGENT_INSIGHT_BASE_URL/api/setup/opencode-uploader" -o "$HOME/.agent-insight/opencode_uploader_client.js"',
        '    echo "⏬ Installing OpenCode commands..."',
        '    mkdir -p "$OPENCODE_CONFIG_DIR/commands"',
        '    curl -sSf "$AGENT_INSIGHT_BASE_URL/api/setup/opencode-commands/si-optimizer" -o "$OPENCODE_CONFIG_DIR/commands/si-optimizer.md"',
        '    echo "⏬ Downloading OpenCode TUI Plugin..."',
        '    curl -sSf "$AGENT_INSIGHT_BASE_URL/api/setup/opencode-tui" -o "$OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.tui.tsx"',
        '    export TUI_PLUGIN_PATH="$OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.tui.tsx"',
        '    export TUI_CONFIG_FILE="$OPENCODE_CONFIG_DIR/tui.json"',
        '    if command -v node &> /dev/null; then',
        '      node - <<\'NODE\'',
        'const fs = require("fs");',
        'const path = require("path");',
        'const file = process.env.TUI_CONFIG_FILE;',
        'const pluginPath = process.env.TUI_PLUGIN_PATH;',
        'let data = {};',
        'try {',
        '  if (fs.existsSync(file)) {',
        '    const text = fs.readFileSync(file, "utf8");',
        '    data = text && text.trim() ? JSON.parse(text) : {};',
        '  }',
        '} catch {}',
        'if (!data || typeof data !== "object") data = {};',
        'const list = Array.isArray(data.plugin) ? data.plugin.slice() : [];',
        'if (pluginPath && !list.includes(pluginPath)) list.push(pluginPath);',
        'data.plugin = list;',
        'fs.mkdirSync(path.dirname(file), { recursive: true });',
        'fs.writeFileSync(file, JSON.stringify(data, null, 2));',
        'NODE',
        '    else',
        '      echo "⚠️  node not found; skip TUI plugin config patch."',
        '    fi',
        'fi',
        '',
        'if [ "$INSTALL_CLAUDE" = "true" ]; then',
        '    echo "🛰️  Claude Code will use official OpenTelemetry logs; no session-file watcher is required."',
        'fi',
        '',
        'if [ "$INSTALL_HERMES" = "true" ]; then',
        '    echo "Installing Agent Insight Hermes plugin..."',
        '    HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"',
        '    HERMES_PLUGIN_DIR="$HERMES_HOME/plugins/agent_insight_hermes"',
        '    mkdir -p "$HERMES_PLUGIN_DIR"',
        '    curl -sSf "$AGENT_INSIGHT_BASE_URL/api/setup/hermes-plugin" -o "$HERMES_PLUGIN_DIR/__init__.py"',
        '    cat > "$HERMES_PLUGIN_DIR/plugin.yaml" <<\'HERMES_PLUGIN_EOF\'',
        'name: agent_insight_hermes',
        'version: 0.2.0',
        'description: Agent Insight telemetry for Hermes',
        'provides_hooks:',
        '  - pre_llm_call',
        '  - post_llm_call',
        '  - pre_api_request',
        '  - post_api_request',
        '  - api_request_error',
        '  - pre_tool_call',
        '  - post_tool_call',
        '  - subagent_start',
        '  - subagent_stop',
        '  - on_session_end',
        'HERMES_PLUGIN_EOF',
        '    if command -v hermes >/dev/null 2>&1; then',
        '        hermes plugins enable agent_insight_hermes || echo "Warning: enable the plugin manually with: hermes plugins enable agent_insight_hermes"',
        '    else',
        '        echo "Warning: hermes command not found. The plugin files were installed; enable agent_insight_hermes after installing Hermes."',
        '    fi',
        'fi',
        '',
        'if [ "$INSTALL_JIUWEN" = "true" ]; then',
        '    echo "⏬ Installing Agent-insight JiuwenSwarm extension..."',
        '    JW_HOME="${JIUWENSWARM_DATA_DIR:-$HOME/.jiuwenswarm}"',
        '    JW_EXT_DIR="$JW_HOME/extensions/agent-insight-observability"',
        '    mkdir -p "$JW_EXT_DIR" "$JW_HOME/config"',
        '    curl -sSf "$AGENT_INSIGHT_BASE_URL/api/setup/jiuwen-extension" -o "$JW_EXT_DIR/extension.py"',
        '    cat > "$JW_EXT_DIR/extension.yaml" <<\'JIUWEN_EXT_EOF\'',
        'id: agent-insight-observability',
        'name: agent-insight-observability',
        'version: 0.1.0',
        'description: Zero-code observability onboarding for JiuwenSwarm via agent-core OTLP.',
        'author: agent-insight',
        'min_jiuwenswarm_version: "0.2.0"',
        'dependencies: {}',
        'config_schema:',
        '  type: object',
        'JIUWEN_EXT_EOF',
        '    echo "✅ JiuwenSwarm extension installed at $JW_EXT_DIR"',
        'fi',
        '',
'if [ "$INSTALL_TRAE" = "true" ]; then',
'    echo "Installing Trae IDE collector..."',
'    echo "  Step 1: Downloading VSIX..."',
'    TMP_VSIX="/tmp/trae-collector.vsix"',
'    curl -sSf "$AGENT_INSIGHT_BASE_URL/api/setup/trae" -o "$TMP_VSIX"',
'',
'    INSTALLED=false',
'    # Try TRAE CLI first (handles extension registration automatically)',
'    if command -v trae-cn &>/dev/null; then',
'        echo "  Step 2: Installing via trae-cn CLI..."',
'        trae-cn --install-extension "$TMP_VSIX" --force 2>/dev/null && INSTALLED=true',
'    fi',
'    if ! $INSTALLED && command -v trae &>/dev/null; then',
'        echo "  Step 2: Installing via trae CLI..."',
'        trae --install-extension "$TMP_VSIX" --force 2>/dev/null && INSTALLED=true',
'    fi',
'',
'    # Fallback: deploy directly to filesystem',
'    if ! $INSTALLED; then',
'        echo "  Step 2: No IDE CLI found, deploying to filesystem..."',
'        # Detect TRAE install directory (trae-cn or trae-cn-server)',
'        TRAE_ROOT=""',
'        for d in "$HOME/.trae-cn" "$HOME/.trae-cn-server"; do',
'            if [ -d "$d" ]; then TRAE_ROOT="$d"; break; fi',
'        done',
'        if [ -z "$TRAE_ROOT" ]; then',
'            TRAE_ROOT="$HOME/.trae-cn-server"',
'            echo "  (TRAE not found, using default: $TRAE_ROOT)"',
'        else',
'            echo "  Found TRAE at: $TRAE_ROOT"',
'        fi',
'',
'        EXT_DIR="$TRAE_ROOT/extensions"',
'        EXT_NAME="agent-insight.agent-insight-trae-collector-0.1.0"',
'        TARGET="$EXT_DIR/$EXT_NAME"',
'',
'        # Step 3: Extract VSIX to extensions directory',
'        echo "  Step 3: Extracting VSIX to $TARGET..."',
'        mkdir -p "$TARGET"',
'        unzip -o "$TMP_VSIX" -d "$TARGET" 2>/dev/null',
'        if [ -d "$TARGET/extension" ]; then',
'            cp -r "$TARGET/extension/"* "$TARGET/" 2>/dev/null',
'            rm -rf "$TARGET/extension" "$TARGET/extension.vsixmanifest" "$TARGET/[Content_Types].xml" 2>/dev/null',
'        fi',
'',
'        # Step 4: Register in extensions.json (remove old + add new)',
'        echo "  Step 4: Registering extension..."',
'        EXT_JSON="$EXT_DIR/extensions.json"',
'        if [ -f "$EXT_JSON" ]; then',
'            export _EXT_JSON="$EXT_JSON" _TARGET="$TARGET" _EXT_NAME="$EXT_NAME"',
"            python3 -c \"import json,time,os;ext_id='agent-insight.agent-insight-trae-collector';ex=json.load(open(os.environ['_EXT_JSON']));ex=[e for e in ex if e.get('identifier',{}).get('id','')!=ext_id];ex.append({'identifier':{'id':ext_id},'version':'0.1.0','location':{'\\$mid':1,'fsPath':os.environ['_TARGET'],'path':os.environ['_TARGET'],'scheme':'file'},'relativeLocation':os.environ['_EXT_NAME'],'metadata':{'installedTimestamp':int(time.time()*1000),'pinned':True,'source':'vsix'}});json.dump(ex,open(os.environ['_EXT_JSON'],'w'),indent=2)\"",
'            echo "  [OK] Extension registered"',
'        else',
'            echo "  [WARN] extensions.json not found, extension registration skipped"',
'        fi',
'        INSTALLED=true',
'    fi',
'',
'    # Clean stale cached copies in Trae IDE bin/ to prevent version mismatch',
'    for TRAE_SERVER in "$HOME/.trae-cn-server" "$HOME/.trae-cn"; do',
'        if [ -d "$TRAE_SERVER/bin" ]; then',
'            find "$TRAE_SERVER/bin" -maxdepth 3 -type d -name "agent-insight*" -exec rm -rf {} + 2>/dev/null',
'        fi',
'    done',
'',
'    rm -f "$TMP_VSIX"',
'',
'    # Step 5: Deploy Hook scripts (via extension setup.sh)',
'    EXT_NAME="agent-insight.agent-insight-trae-collector-0.1.0"',
'    for TRAE_BASE in "$HOME/.trae-cn" "$HOME/.trae-cn-server"; do',
'        SETUP_SCRIPT="$TRAE_BASE/extensions/$EXT_NAME/setup.sh"',
'        if [ -f "$SETUP_SCRIPT" ]; then',
'            echo "  Step 5: Deploying Hook scripts..."',
'            bash "$SETUP_SCRIPT"',
'            break',
'        fi',
'    done',
'',
'    echo "  [OK] Trae IDE collector installed"',
'    echo "  [NOTE] Restart TRAE IDE to activate"',
'fi',
        '',
        '# 4. Configure ~/.agent-insight/.env',
        'AGENT_INSIGHT_CONFIG_FILE="$HOME/.agent-insight/.env"',
        'EXISTING_KEY=""',
        'EXISTING_HOST=""',
        'EXISTING_SHOW_TASK_STATS=""',
        'if [ -f "$AGENT_INSIGHT_CONFIG_FILE" ]; then',
        '    EXISTING_KEY=$(grep \'^AGENT_INSIGHT_API_KEY=\' "$AGENT_INSIGHT_CONFIG_FILE" | head -n 1 | cut -d\'=\' -f2-)',
        '    EXISTING_HOST=$(grep \'^AGENT_INSIGHT_HOST=\' "$AGENT_INSIGHT_CONFIG_FILE" | head -n 1 | cut -d\'=\' -f2-)',
        '    EXISTING_SHOW_TASK_STATS=$(grep \'^AGENT_INSIGHT_SHOW_TASK_STATS=\' "$AGENT_INSIGHT_CONFIG_FILE" | head -n 1 | cut -d\'=\' -f2-)',
        'fi',
        '',
        '# -- API Key Logic --',
        'FINAL_KEY="${AGENT_INSIGHT_SETUP_API_KEY:-$EXISTING_KEY}"',
        'if [ -n "$AGENT_INSIGHT_SETUP_API_KEY" ]; then',
        '    echo "🔑 Using API Key from setup URL."',
        'elif [ -n "$EXISTING_KEY" ]; then',
        '    echo "🔑 Found existing API Key."',
        '    read -p "👉 Use existing key? (y/N, Default: y): " USE_EXISTING < /dev/tty',
        '    if [[ "$USE_EXISTING" =~ ^[Nn]$ ]]; then',
        '        read -p "👉 Please enter your NEW API Key: " FINAL_KEY < /dev/tty',
        '    fi',
        'else',
        '    echo "🔑 AGENT_INSIGHT_API_KEY is not set."',
        '    read -p "👉 Please enter your API Key: " FINAL_KEY < /dev/tty',
        'fi',
        '',
        '# -- Host Logic --',
        'FINAL_HOST="$AGENT_INSIGHT_HOST"',
        'if [ -n "$EXISTING_HOST" ] && [ "$EXISTING_HOST" != "$AGENT_INSIGHT_HOST" ]; then',
        '    echo "🌐 Current Host in config: $EXISTING_HOST"',
        '    echo "🌐 New Host detected: $AGENT_INSIGHT_HOST"',
        '    read -p "👉 Change to new Host? (y/N, Default: y): " CHANGE_HOST < /dev/tty',
        '    if [[ "$CHANGE_HOST" =~ ^[Nn]$ ]]; then',
        '        FINAL_HOST="$EXISTING_HOST"',
        '    fi',
        'elif [ -z "$EXISTING_HOST" ]; then',
        '    FINAL_HOST="$AGENT_INSIGHT_HOST"',
        'fi',
        '',
        'FINAL_SHOW_TASK_STATS="$EXISTING_SHOW_TASK_STATS"',
        'if [ -z "$FINAL_SHOW_TASK_STATS" ]; then',
        '    FINAL_SHOW_TASK_STATS="true"',
        'fi',
        '',
        'if [ -z "$FINAL_KEY" ]; then',
        '    echo "⚠️  Warning: No API Key provided. Telemetry upload will fail until you set it in $AGENT_INSIGHT_CONFIG_FILE"',
        'fi',
        '',
        'echo "⚙️  Updating configuration..."',
        'touch "$AGENT_INSIGHT_CONFIG_FILE"',
        'cp "$AGENT_INSIGHT_CONFIG_FILE" "${AGENT_INSIGHT_CONFIG_FILE}.bak"',
        'grep -v "^AGENT_INSIGHT_HOST=" "${AGENT_INSIGHT_CONFIG_FILE}.bak" | grep -v "^AGENT_INSIGHT_API_KEY=" | grep -v "^AGENT_INSIGHT_SHOW_TASK_STATS=" | grep -v "^AGENT_INSIGHT_RETENTION_DAYS=" | grep -v "^AGENT_INSIGHT_OPENCODE_OTEL_ENABLE=" | grep -v "^AGENT_INSIGHT_OPENCODE_SPOOL_DIR=" | grep -v "^AGENT_INSIGHT_OPENCODE_UPLOADER=" | grep -v "^AGENT_INSIGHT_CLAUDE_OTEL_SPOOL_DIR=" | grep -v "^AGENT_INSIGHT_CODEAGENT_OTEL_SPOOL_DIR=" | grep -v "^AGENT_INSIGHT_CLAUDE_OTEL_RAW_API_BODIES=" | grep -v "^AGENT_INSIGHT_MAX_TOOL_IO=" | grep -v "^AGENT_INSIGHT_MAX_EVENT_STRING=" | grep -v "^AGENT_INSIGHT_OPENCODE_UPLOAD_COOLDOWN_MS=" > "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_HOST=$FINAL_HOST" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_API_KEY=$FINAL_KEY" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_SHOW_TASK_STATS=$FINAL_SHOW_TASK_STATS" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_RETENTION_DAYS=10" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_OPENCODE_OTEL_ENABLE=true" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_OPENCODE_SPOOL_DIR=$HOME/.agent-insight/otel_data/opencode" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_OPENCODE_UPLOADER=$HOME/.agent-insight/opencode_uploader_client.js" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_CLAUDE_OTEL_SPOOL_DIR=$HOME/.agent-insight/otel_data/claude" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_CLAUDE_OTEL_RAW_API_BODIES=file:$HOME/.agent-insight/claude_raw_bodies" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_CODEAGENT_OTEL_SPOOL_DIR=$HOME/.agent-insight/otel_data/codeagent" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_MAX_TOOL_IO=4000" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_MAX_EVENT_STRING=20000" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'echo "AGENT_INSIGHT_OPENCODE_UPLOAD_COOLDOWN_MS=15000" >> "$AGENT_INSIGHT_CONFIG_FILE"',
        'rm "${AGENT_INSIGHT_CONFIG_FILE}.bak"',
        'echo "✅ Configuration updated at $AGENT_INSIGHT_CONFIG_FILE"',
        '',
        '# 6.4 Configure Agent Insight Hermes plugin',
        'if [ "$INSTALL_HERMES" = "true" ]; then',
        '    HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"',
        '    HERMES_PLUGIN_DIR="$HERMES_HOME/plugins/agent_insight_hermes"',
        '    mkdir -p "$HERMES_PLUGIN_DIR"',
        '    cat > "$HERMES_PLUGIN_DIR/config.json" <<HERMES_CONFIG_EOF',
        '{',
        '  "host": "${FINAL_HOST%/}",',
        '  "api_key": "$FINAL_KEY",',
        '  "service_name": "hermes",',
        '  "max_content_chars": 200000,',
        '  "spool_dir": "$HOME/.agent-insight/data/hermes-otel-spool",',
        '  "log_file": "$HOME/.agent-insight/logs/hermes-plugin.log"',
        '}',
        'HERMES_CONFIG_EOF',
        '    echo "Agent Insight Hermes config written to $HERMES_PLUGIN_DIR/config.json"',
        'fi',
        '',
        '# 6.45 Configure JiuwenSwarm telemetry (workspace config/.env, read by the extension)',
        'if [ "$INSTALL_JIUWEN" = "true" ]; then',
        '    JW_HOME="${JIUWENSWARM_DATA_DIR:-$HOME/.jiuwenswarm}"',
        '    JW_ENV="$JW_HOME/config/.env"',
        '    JW_EXT_PARENT="$JW_HOME/extensions"',
        '    JW_OTLP_HOST="$FINAL_HOST"',
        '    case "$JW_OTLP_HOST" in http://*|https://*) ;; *) JW_OTLP_HOST="http://$JW_OTLP_HOST" ;; esac',
        '    JW_OTLP_ENDPOINT="${JW_OTLP_HOST%/}/api/ingest/otel/v1/traces"',
        '    mkdir -p "$JW_HOME/config"',
        '    touch "$JW_ENV"',
        '    cp "$JW_ENV" "${JW_ENV}.bak"',
        '    PREV_EXT_DIRS=$(grep \'^EXTENSION_DIRS=\' "${JW_ENV}.bak" | head -n 1 | cut -d\'=\' -f2-)',
        '    PREV_EXT_DIRS="${PREV_EXT_DIRS#\\"}"; PREV_EXT_DIRS="${PREV_EXT_DIRS%\\"}"',
        '    if [ -z "$PREV_EXT_DIRS" ]; then PREV_EXT_DIRS="jiuwenswarm/extensions"; fi',
        '    case ";$PREV_EXT_DIRS;" in',
        '        *";$JW_EXT_PARENT;"*) NEW_EXT_DIRS="$PREV_EXT_DIRS" ;;',
        '        *) NEW_EXT_DIRS="$PREV_EXT_DIRS;$JW_EXT_PARENT" ;;',
        '    esac',
        '    grep -v \'^OTEL_ENABLED=\' "${JW_ENV}.bak" | grep -v \'^AGENT_INSIGHT_OTLP_ENDPOINT=\' | grep -v \'^AGENT_INSIGHT_API_KEY=\' | grep -v \'^EXTENSION_DIRS=\' > "$JW_ENV"',
        '    echo "OTEL_ENABLED=true" >> "$JW_ENV"',
        '    echo "AGENT_INSIGHT_OTLP_ENDPOINT=$JW_OTLP_ENDPOINT" >> "$JW_ENV"',
        '    echo "AGENT_INSIGHT_API_KEY=$FINAL_KEY" >> "$JW_ENV"',
        '    echo "EXTENSION_DIRS=$NEW_EXT_DIRS" >> "$JW_ENV"',
        '    rm -f "${JW_ENV}.bak"',
        '    echo "✅ JiuwenSwarm telemetry configured -> $JW_OTLP_ENDPOINT (service=jiuwenswarm)"',
        'fi',
        '',
        '# 6.5 Configure Claude Code official OTel logs',
        'if [ "$INSTALL_CLAUDE" = "true" ]; then',
        '    cat > "$HOME/.agent-insight/claude_otel_env.sh" << \'CLAUDE_OTEL_EOF\'',
        '# Agent-Insight Claude Code OpenTelemetry integration',
        'unalias claude 2>/dev/null || true',
        '',
        '_skill_insight_claude_load_env() {',
        '  if [ -f "$HOME/.agent-insight/.env" ]; then',
        '    set -a',
        '    . "$HOME/.agent-insight/.env"',
        '    set +a',
        '  fi',
        '}',
        '',
        'claude() {',
        '  _skill_insight_claude_load_env',
        '  local _si_host="${AGENT_INSIGHT_HOST:-127.0.0.1:3000}"',
        '  case "$_si_host" in http://*|https://*) ;; *) _si_host="http://$_si_host" ;; esac',
        '  _si_host="${_si_host%/}"',
        '  mkdir -p "$HOME/.agent-insight/claude_raw_bodies" 2>/dev/null || true',
        '  env \\',
        '    CLAUDE_CODE_ENABLE_TELEMETRY=1 \\',
        '    OTEL_LOGS_EXPORTER=otlp \\',
        '    OTEL_METRICS_EXPORTER="${OTEL_METRICS_EXPORTER:-none}" \\',
        '    OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/json \\',
        '    OTEL_EXPORTER_OTLP_LOGS_ENDPOINT="$_si_host/api/ingest/otel/v1/logs" \\',
        '    OTEL_EXPORTER_OTLP_HEADERS="x-witty-api-key=${AGENT_INSIGHT_API_KEY:-}" \\',
        '    OTEL_LOG_USER_PROMPTS=1 \\',
        '    OTEL_LOG_TOOL_DETAILS=1 \\',
        '    OTEL_LOG_TOOL_CONTENT=1 \\',
        '    OTEL_LOG_RAW_API_BODIES="${AGENT_INSIGHT_CLAUDE_OTEL_RAW_API_BODIES:-file:$HOME/.agent-insight/claude_raw_bodies}" \\',
        '    claude "$@"',
        '}',
        'CLAUDE_OTEL_EOF',
        '    SHELL_RC="$HOME/.zshrc"',
        '    [ -f "$HOME/.bashrc" ] && SHELL_RC="$HOME/.bashrc"',
        '    if [ -f "$SHELL_RC" ] && ! grep -q "\\.agent-insight/claude_otel_env\\.sh" "$SHELL_RC"; then',
        '        echo "" >> "$SHELL_RC"',
        '        echo "# Agent-Insight Claude Code OTel" >> "$SHELL_RC"',
        '        echo "source \\"$HOME/.agent-insight/claude_otel_env.sh\\"" >> "$SHELL_RC"',
        '    fi',
        '    echo "✅ Claude Code OTel env installed at $HOME/.agent-insight/claude_otel_env.sh"',
        '    echo "   Restart your terminal or run: source $HOME/.agent-insight/claude_otel_env.sh"',
        '    pkill -f "claude_watcher_client.ts" 2>/dev/null || true',
        '    rm -f "$HOME/.agent-insight/claude_watcher_client.ts" "$HOME/.agent-insight/start_claude_watcher.sh" "$HOME/.agent-insight/stop_claude_watcher.sh" "$HOME/.agent-insight/claude_watcher.pid"',
        '    echo "🧹 Removed legacy Claude session-file watcher if it was installed."',
        'fi',
        '',
        '# 6.6 Configure OpenClaw official OTel logs',
        '# 6.6a Configure CodeAgent OpenTelemetry wrapper',
        'if [ "$INSTALL_CODEAGENT" = "true" ]; then',
        '    cat > "$HOME/.agent-insight/codeagent_otel_env.sh" << \'CODEAGENT_OTEL_EOF\'',
        '# Agent-Insight CodeAgent OpenTelemetry integration',
        'unalias codeagent 2>/dev/null || true',
        '',
        '_skill_insight_codeagent_load_env() {',
        '  if [ -f "$HOME/.agent-insight/.env" ]; then',
        '    set -a',
        '    . "$HOME/.agent-insight/.env"',
        '    set +a',
        '  fi',
        '}',
        '',
        'codeagent() {',
        '  _skill_insight_codeagent_load_env',
        '  local _si_host="${AGENT_INSIGHT_HOST:-127.0.0.1:3000}"',
        '  case "$_si_host" in http://*|https://*) ;; *) _si_host="http://$_si_host" ;; esac',
        '  _si_host="${_si_host%/}"',
        '  env \\',
        '    CODEAGENT3_ENABLE_TELEMETRY=1 \\',
        '    OTEL_EXPORTER_OTLP_ENDPOINT="$_si_host/api/ingest/otel" \\',
        '    OTEL_EXPORTER_OTLP_PROTOCOL=http/json \\',
        '    OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/json \\',
        '    OTEL_EXPORTER_OTLP_HEADERS="x-witty-api-key=${AGENT_INSIGHT_API_KEY:-}" \\',
        '    codeagent "$@"',
        '}',
        'CODEAGENT_OTEL_EOF',
        '    SHELL_RC="$HOME/.zshrc"',
        '    [ -f "$HOME/.bashrc" ] && SHELL_RC="$HOME/.bashrc"',
        '    if [ -f "$SHELL_RC" ] && ! grep -q "codeagent_otel_env.sh" "$SHELL_RC"; then',
        '        echo "" >> "$SHELL_RC"',
        '        echo "# Agent-Insight CodeAgent OTel" >> "$SHELL_RC"',
        '        echo "source \\"$HOME/.agent-insight/codeagent_otel_env.sh\\"" >> "$SHELL_RC"',
        '    fi',
        '    echo "✅ CodeAgent OTel env installed at $HOME/.agent-insight/codeagent_otel_env.sh"',
        '    echo "   Restart your terminal, then run: codeagent"',
        '    echo "   CodeAgent may still send traces/metrics; Agent Insight accepts and discards those signals."',
        'fi',
        '',
        'if [ "$INSTALL_OPENCLAW" = "true" ]; then',
        '    cat > "$HOME/.agent-insight/openclaw_otel_env.sh" << \'OPENCLAW_OTEL_EOF\'',
        '# Agent-Insight OpenClaw OpenTelemetry integration',
        'unalias openclaw 2>/dev/null || true',
        '',
        '_skill_insight_openclaw_load_env() {',
        '  if [ -f "$HOME/.agent-insight/.env" ]; then',
        '    set -a',
        '    . "$HOME/.agent-insight/.env"',
        '    set +a',
        '  fi',
        '}',
        'openclaw() {',
        '  _skill_insight_openclaw_load_env',
        '  local _si_host="${AGENT_INSIGHT_HOST:-127.0.0.1:3000}"',
        '  case "$_si_host" in http://*|https://*) ;; *) _si_host="http://$_si_host" ;; esac',
        '  _si_host="${_si_host%/}"',
        '  env \\',
        '    CLAW_ENABLE_TELEMETRY=1 \\',
        '    OTEL_LOGS_EXPORTER=otlp \\',
        '    OTEL_METRICS_EXPORTER="${OTEL_METRICS_EXPORTER:-none}" \\',
        '    OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/json \\',
        '    OTEL_EXPORTER_OTLP_LOGS_ENDPOINT="$_si_host/api/ingest/otel/v1/logs" \\',
        '    OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/json \\',
        '    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT="$_si_host/api/ingest/otel/v1/traces" \\',
        '    OTEL_EXPORTER_OTLP_HEADERS="x-witty-api-key=${AGENT_INSIGHT_API_KEY:-}" \\',
        '    OTEL_LOG_USER_PROMPTS=1 \\',
        '    OTEL_LOG_TOOL_DETAILS=1 \\',
        '    OTEL_LOG_TOOL_CONTENT=1 \\',
        '    openclaw "$@"',
        '}',
        'OPENCLAW_OTEL_EOF',
        '    SHELL_RC="$HOME/.zshrc"',
        '    [ -f "$HOME/.bashrc" ] && SHELL_RC="$HOME/.bashrc"',
        '    if [ -f "$SHELL_RC" ] && ! grep -q "openclaw_otel_env.sh" "$SHELL_RC"; then',
        '        echo "" >> "$SHELL_RC"',
        '        echo "# Agent-Insight OpenClaw OTel" >> "$SHELL_RC"',
        '        echo "source \\"$HOME/.agent-insight/openclaw_otel_env.sh\\"" >> "$SHELL_RC"',
        '    fi',
        '    echo "✅ OpenClaw OTel env installed at $HOME/.agent-insight/openclaw_otel_env.sh"',
        '    echo "   Restart your terminal or run: source $HOME/.agent-insight/openclaw_otel_env.sh"',
        '    echo ""',
        '    echo "============================================"',
        '    echo "  OpenClaw OTel -- 纯配置方式（复制 env 块）"',
        '    echo "============================================"',
        '    echo ""',
        '    echo "  export CLAW_ENABLE_TELEMETRY=1"',
        '    echo "  export OTEL_LOGS_EXPORTER=otlp"',
        '    echo "  export OTEL_METRICS_EXPORTER=none"',
        '    echo "  export OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/protobuf"',
        '    echo "  export OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://127.0.0.1:3000/api/ingest/otel/v1/traces"',
        '    echo "  export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf"',
        '    echo "  export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://127.0.0.1:3000/api/ingest/otel/v1/traces"',
        '    echo "  export OTEL_EXPORTER_OTLP_HEADERS=x-witty-api-key=<your-api-key>"',
        '    echo "  export OTEL_SERVICE_NAME=openclaw"',
        '    echo ""',
        '    echo "---"',
        '    echo "!! OTel 纯配置方式 与 Watcher 模式互斥。"',
        '    echo "   选择一种方式即可，不要同时启用两种。"',
        '    echo "   如已启用 watcher，请移除以上 OTel 环境变量避免重复。"',
        '    echo ""',
        'fi',
        '',
        '',
        '# 7. Create Watcher Startup/Stop Scripts',
        'NEEDS_WATCHER_SCRIPTS=false',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then',
        '    NEEDS_WATCHER_SCRIPTS=true',
        'fi',
        '',
        'if [ "$NEEDS_WATCHER_SCRIPTS" = "true" ]; then',
        '    echo ""',
        '    echo "📝 Creating watcher management scripts..."',
        '',
        // OpenCode uploader: 5-min fallback daemon. Plugin-side kickUploader is
        // the primary trigger (low latency, fires on session.idle); this daemon
        // catches anything that didn't get uploaded — e.g. when opencode exits
        // before the detached child finished POSTing. The mtime gate inside the
        // uploader keeps each idle cycle around ~5ms.
        '    if [ "$INSTALL_OPENCODE" = "true" ]; then',
        '        cat > "$HOME/.agent-insight/start_opencode_uploader.sh" << \'OPENCODE_UP_EOF\'',
        '#!/bin/bash',
        '# Kill any previous instance (the sentinel string lets pkill -f find the loop).',
        'pkill -f "skill-insight-opencode-uploader-loop" 2>/dev/null',
        'pkill -f "opencode_uploader_client.js" 2>/dev/null',
        'mkdir -p "$HOME/.agent-insight/logs"',
        'INTERVAL_SEC="${AGENT_INSIGHT_OPENCODE_UPLOADER_INTERVAL_SEC:-300}"',
        'LOG_FILE="$HOME/.agent-insight/logs/opencode_uploader.log"',
        'if command -v node >/dev/null 2>&1; then',
        '    RUNTIME=node',
        'elif command -v bun >/dev/null 2>&1; then',
        '    RUNTIME=bun',
        'else',
        '    echo "[$(date)] Skipped: node/bun not installed" >> "$LOG_FILE"',
        '    exit 0',
        'fi',
        '# Loop body has a sentinel comment so `pkill -f skill-insight-opencode-uploader-loop` matches.',
        'nohup bash -c "',
        '# skill-insight-opencode-uploader-loop',
        'while true; do',
        '    \\"$RUNTIME\\" \\"$HOME/.agent-insight/opencode_uploader_client.js\\" >> \\"$LOG_FILE\\" 2>&1',
        '    sleep \\"$INTERVAL_SEC\\"',
        'done" > /dev/null 2>&1 &',
        'echo $! > "$HOME/.agent-insight/opencode_uploader.pid"',
        'echo "OpenCode uploader daemon started with PID $(cat $HOME/.agent-insight/opencode_uploader.pid) (interval=${INTERVAL_SEC}s)"',
        'OPENCODE_UP_EOF',
        '        chmod +x "$HOME/.agent-insight/start_opencode_uploader.sh"',
        '',
        '        cat > "$HOME/.agent-insight/stop_opencode_uploader.sh" << \'STOP_OPENCODE_UP_EOF\'',
        '#!/bin/bash',
        'pkill -f "skill-insight-opencode-uploader-loop" 2>/dev/null',
        'pkill -f "opencode_uploader_client.js" 2>/dev/null',
        'PID_FILE="$HOME/.agent-insight/opencode_uploader.pid"',
        'if [ -f "$PID_FILE" ]; then kill "$(cat $PID_FILE)" 2>/dev/null; rm -f "$PID_FILE"; fi',
        'echo "OpenCode uploader daemon stopped"',
        'STOP_OPENCODE_UP_EOF',
        '        chmod +x "$HOME/.agent-insight/stop_opencode_uploader.sh"',
        '    fi',
        '',
        '    cat > "$HOME/.agent-insight/start_watchers.sh" << \'WATCHER_HEADER\'',
        '#!/bin/bash',
        'echo "Starting Agent-Insight watchers..."',
        'WATCHER_HEADER',
        '    if [ "$INSTALL_OPENCODE" = "true" ]; then echo \'"$HOME/.agent-insight/start_opencode_uploader.sh"\' >> "$HOME/.agent-insight/start_watchers.sh"; fi',
        '    echo \'echo "All watchers started!"\' >> "$HOME/.agent-insight/start_watchers.sh"',
        '    chmod +x "$HOME/.agent-insight/start_watchers.sh"',
        '',
        '    cat > "$HOME/.agent-insight/stop_watchers.sh" << \'STOP_HEADER\'',
        '#!/bin/bash',
        'echo "Stopping Agent-Insight watchers..."',
        'STOP_HEADER',
        '    if [ "$INSTALL_OPENCODE" = "true" ]; then echo \'"$HOME/.agent-insight/stop_opencode_uploader.sh"\' >> "$HOME/.agent-insight/stop_watchers.sh"; fi',
        '    echo \'echo "All watchers stopped!"\' >> "$HOME/.agent-insight/stop_watchers.sh"',
        '    chmod +x "$HOME/.agent-insight/stop_watchers.sh"',
        'fi',
        '',
        '# 8. Start Watchers Now',
        'if [ "$NEEDS_WATCHER_SCRIPTS" = "true" ]; then',
        '    echo ""',
        '    echo "🚀 Starting telemetry watchers..."',
        '    if command -v npx &> /dev/null; then',
        '        "$HOME/.agent-insight/start_watchers.sh"',
        '    else',
        '        echo "⚠️  Node.js (npx) not found. Skipping watcher startup."',
        '    fi',
        'fi',
        '',
        '# 10. Final Summary',
        'echo ""',
        'echo "🌟 Agent-Insight Telemetry: READY"',
        'echo "------------------------------------------------"',
        'echo "Installed Components:"',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then echo "  ✅ OpenCode Plugin: $OPENCODE_CONFIG_DIR/plugins/Witty-Skill-Insight.ts"; fi',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then echo "  ✅ OpenCode Command: ~/.config/opencode/commands/si-optimizer.md"; fi',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then echo "  ✅ OpenCode Uploader Daemon: ~/.agent-insight/opencode_uploader_client.js (5-min poll)"; fi',
        'if [ "$INSTALL_CLAUDE" = "true" ]; then echo "  ✅ Claude Code OTel: ~/.agent-insight/claude_otel_env.sh"; fi',
        'if [ "$INSTALL_CODEAGENT" = "true" ]; then echo "  ✅ CodeAgent OTel: ~/.agent-insight/codeagent_otel_env.sh"; fi',
        'if [ "$INSTALL_OPENCLAW" = "true" ]; then echo "  ✅ OpenClaw OTel: ~/.agent-insight/openclaw_otel_env.sh"; fi',
        'if [ "$INSTALL_HERMES" = "true" ]; then echo "  ✅ Agent Insight Hermes Plugin: ${HERMES_HOME:-$HOME/.hermes}/plugins/agent_insight_hermes/config.json"; fi',
        'if [ "$INSTALL_JIUWEN" = "true" ]; then echo "  ✅ JiuwenSwarm Extension: ${JIUWENSWARM_DATA_DIR:-$HOME/.jiuwenswarm}/extensions/agent-insight-observability (telemetry in config/.env)"; fi',
        'if [ "$INSTALL_TRAE" = "true" ]; then echo "  [OK] Trae IDE Collector: ~/.trae-cn-server/extensions/agent-insight.agent-insight-trae-collector-0.1.0"; fi',
        '',
        'if [ "$NEEDS_WATCHER_SCRIPTS" = "true" ]; then',
        '    echo ""',
        '    echo "Watcher Management:"',
        '    echo "  Start all:    ~/.agent-insight/start_watchers.sh"',
        '    echo "  Stop all:     ~/.agent-insight/stop_watchers.sh"',
        '    echo "  Logs:         ~/.agent-insight/logs/"',
        'fi',
        '',
        'echo ""',
        'echo "Usage:"',
        'if [ "$INSTALL_OPENCODE" = "true" ]; then echo "  1. Run: opencode run \'hello\'"; fi',
        'if [ "$INSTALL_CLAUDE" = "true" ]; then echo "  2. Restart terminal, then run: claude"; fi',
        'if [ "$INSTALL_HERMES" = "true" ]; then echo "  3. Restart Hermes or start a new Hermes conversation"; fi',
        'if [ "$INSTALL_OPENCLAW" = "true" ]; then echo "  4. Restart terminal, then run: openclaw"; fi',
        'if [ "$INSTALL_CODEAGENT" = "true" ]; then echo "  5. Restart terminal, then run: codeagent"; fi',
        'if [ "$INSTALL_JIUWEN" = "true" ]; then echo "  6. Restart JiuwenSwarm (agentserver), then start a conversation"; fi',
        'if [ "$INSTALL_TRAE" = "true" ]; then echo "  7. Restart TRAE IDE to activate the collector"; fi',
        'echo "------------------------------------------------"',
    ];
    return lines.join('\n');
}

function generatePowerShellScript(host: string, baseUrl: string, apiKey: string, preselected: { value: string; label: string }[]): string {
    const lines = [
        '# =============================================================================',
        '# Agent-insight One-Click Setup (PowerShell)',
        '# =============================================================================',
        '',
        '$AGENT_INSIGHT_HOST = "' + powerShellDoubleQuoted(host) + '"',
        '$AGENT_INSIGHT_BASE_URL = "' + powerShellDoubleQuoted(baseUrl) + '"',
        '$AGENT_INSIGHT_SETUP_API_KEY = "' + powerShellDoubleQuoted(apiKey) + '"',
        '',
        'Write-Host "🚀 Fetching Agent-insight telemetry components from $AGENT_INSIGHT_BASE_URL..."',
        '',
        '# 0. Check Node.js version',
        '$nodeCmd = Get-Command node -ErrorAction SilentlyContinue',
        'if (-not $nodeCmd) {',
        '    Write-Host "❌ Error: Node.js is not installed." -ForegroundColor Red',
        '    Write-Host "   Agent-insight requires Node.js 20 or higher."',
        '    Write-Host "   Please install Node.js: https://nodejs.org/"',
        '    exit 1',
        '}',
        '',
        '$nodeVersion = (node -v 2>$null) -replace "^v", ""',
        '$nodeMajor = $nodeVersion.Split(".")[0]',
        'if ([int]$nodeMajor -lt 20) {',
        '    Write-Host "❌ Error: Node.js version $nodeVersion is not supported." -ForegroundColor Red',
        '    Write-Host "   Agent-insight requires Node.js 20 or higher."',
        '    Write-Host "   Please upgrade your Node.js version: https://nodejs.org/"',
        '    exit 1',
        '}',
        'Write-Host "✅ Node.js version: $nodeVersion"',
        '',
        '# 1. Setup Directories',
        '$homeDir = $env:USERPROFILE',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.agent-insight" | Out-Null',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.agent-insight\\logs" | Out-Null',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.opencode\\plugins" | Out-Null',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.opencode\\skills" | Out-Null',
        'New-Item -ItemType Directory -Force -Path "$homeDir\\.claude\\projects" | Out-Null',
        'New-Item -ItemType Directory -Force -Path ".opencode\\skills" | Out-Null',
        'Write-Host "📂 Created necessary directories"',
        '',
        // 同 bash 侧：安装页勾选后跳过 inquirer 交互，免去 npm registry 依赖。
        '# 2. Framework selection',
        '$SELECTED_FRAMEWORKS = "' + preselected.map(f => f.value).join(',') + '"',
        'if ($SELECTED_FRAMEWORKS) {',
        '    Write-Host ""',
        '    Write-Host "✅ 将安装以下组件: ' + powerShellDoubleQuoted(preselected.map(f => f.label).join('、')) + '"',
        '    Write-Host ""',
        '} else {',
        '# 2b. Interactive Framework Selection with inquirer',
        'Write-Host ""',
        '',
        '$SELECTOR_SCRIPT = "$homeDir\\.agent-insight\\framework_selector.mjs"',
        '$SELECTOR_RESULT = "$homeDir\\.agent-insight\\.selector_result"',
        '',
        '# Install inquirer and tsx if not already installed',
        'Set-Location "$homeDir\\.agent-insight"',
        'if (-not (Test-Path "package.json")) {',
        '    \'{"name": "agent-insight-setup", "version": "1.0.0", "type": "module", "dependencies": {}}\' | Out-File -FilePath "package.json" -Encoding utf8',
        '}',
        'if (-not (Test-Path "node_modules\\inquirer") -or -not (Test-Path "node_modules\\tsx")) {',
        '    Write-Host "📦 Installing dependencies for interactive selection..."',
        '    npm install inquirer tsx --save 2>$null',
        '}',
        '',
        '$selectorContent = @\'',
        'import inquirer from \'inquirer\';',
        'import fs from \'fs\';',
        '',
        'const frameworks = [',
        '    { name: \'OpenCode\', value: \'opencode\' },',
        '    { name: \'OpenClaw\', value: \'openclaw\' },',
        '    { name: \'Claude Code\', value: \'claude\' },',
        '    { name: \'CodeAgent\', value: \'codeagent\' },',
        '    { name: \'Hermes\', value: \'hermes\' },',
        '    { name: \'JiuwenSwarm\', value: \'jiuwen\' },',
        '    { name: \'Trae IDE\', value: \'trae\' }',
        '];',
        '',
        'async function select() {',
        '    console.log(\'\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'╔══════════════════════════════════════════════════════════╗\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'║                                                          ║\');',
        '    console.log(\'\\x1b[1m\\x1b[36m%s\\x1b[0m\', \'║                 ✨ Agent-insight ✨                      ║\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'║                                                          ║\');',
        '    console.log(\'\\x1b[36m%s\\x1b[0m\', \'╚══════════════════════════════════════════════════════════╝\');',
        '    console.log(\'\');',
        '    console.log(\'\\x1b[90m%s\\x1b[0m\', \'  提示: ↑↓ 移动  |  空格 选择  |  a 全选  |  i 反选  |  Enter 确认\');',
        '    console.log(\'\');',
        '',
        '    const answers = await inquirer.prompt([',
        '        {',
        '            type: \'checkbox\',',
        '            name: \'frameworks\',',
        '            message: \'集成到：\',',
        '            choices: frameworks,',
        '            default: [\'opencode\'],',
        '            pageSize: 10,',
        '            loop: false',
        '        }',
        '    ]);',
        '',
        '    const selected = answers.frameworks;',
        '    ',
        '    if (selected.length > 0) {',
        '        console.log(\'\');',
        '        console.log(\'\\x1b[32m%s\\x1b[0m\', \'✅ 将安装以下组件:\');',
        '        selected.forEach(fw => {',
        '            const name = frameworks.find(f => f.value === fw)?.name || fw;',
        '            console.log(\'\\x1b[32m%s\\x1b[0m\', \'   • \' + name);',
        '        });',
        '        console.log(\'\');',
        '    } else {',
        '        console.log(\'\');',
        '        console.log(\'\\x1b[33m%s\\x1b[0m\', \'⚠️  未选择任何组件，将不进行安装。\');',
        '        console.log(\'\');',
        '    }',
        '',
        '    const resultFile = process.env.SELECTOR_RESULT_FILE || process.env.USERPROFILE + \'\\\\.agent-insight\\\\.selector_result\';',
        '    fs.writeFileSync(resultFile, selected.join(\',\'));',
        '}',
        '',
        'select().catch(err => {',
        '    console.error(\'Error:\', err);',
        '    process.exit(1);',
        '});',
        '\'@',
        '',
        'Set-Content -Path $SELECTOR_SCRIPT -Value $selectorContent -Encoding UTF8',
        '',
        '# Run the selector interactively',
        '$env:SELECTOR_RESULT_FILE = $SELECTOR_RESULT',
        'Set-Location "$homeDir\\.agent-insight"',
        'npx -y tsx $SELECTOR_SCRIPT',
        '',
        '# Read the selection result from file',
        'if (Test-Path $SELECTOR_RESULT) {',
        '    $SELECTED_FRAMEWORKS = Get-Content $SELECTOR_RESULT',
        '    Remove-Item $SELECTOR_RESULT -Force',
        '} else {',
        '    $SELECTED_FRAMEWORKS = ""',
        '}',
        '}',
        '',
        '# Set installation flags based on selection',
        '$INSTALL_OPENCODE = $false',
        '$INSTALL_CLAUDE = $false',
        '$INSTALL_OPENCLAW = $false',
        '$INSTALL_CODEAGENT = $false',
        '$INSTALL_HERMES = $false',
        '$INSTALL_JIUWEN = $false',
        '$INSTALL_TRAE = $false',
        '',
        'if ($SELECTED_FRAMEWORKS -match "opencode") {',
        '    $INSTALL_OPENCODE = $true',
        '}',
        'if ($SELECTED_FRAMEWORKS -match "claude") {',
        '    $INSTALL_CLAUDE = $true',
        '}',
        'if ($SELECTED_FRAMEWORKS -match "openclaw") {',
        '    $INSTALL_OPENCLAW = $true',
        '}',
        'if ($SELECTED_FRAMEWORKS -match "codeagent") {',
        '    $INSTALL_CODEAGENT = $true',
        '}',
        'if ($SELECTED_FRAMEWORKS -match "hermes") {',
        '    $INSTALL_HERMES = $true',
        '}',
        'if ($SELECTED_FRAMEWORKS -match "jiuwen") {',
        '    $INSTALL_JIUWEN = $true',
        '}',
        'if ($SELECTED_FRAMEWORKS -match "trae") {',
        '    $INSTALL_TRAE = $true',
        '}',
        '',
        '# Exit if nothing selected',
        'if (-not $INSTALL_OPENCODE -and -not $INSTALL_CLAUDE -and -not $INSTALL_OPENCLAW -and -not $INSTALL_CODEAGENT -and -not $INSTALL_HERMES -and -not $INSTALL_JIUWEN -and -not $INSTALL_TRAE) {',
        '    Write-Host "⚠️  未选择任何框架组件，将跳过插件安装。"',
        '    Write-Host "   继续执行配置步骤..."',
        '    Write-Host ""',
        '}',
        '',
        '# 3. Download Components',
        'if ($INSTALL_OPENCODE) {',
        '    Write-Host "⏬ Downloading OpenCode Plugin..."',
        '    $opencodeConfigDir = Join-Path $homeDir ".config\\opencode"',
        '    New-Item -ItemType Directory -Path (Join-Path $opencodeConfigDir "plugins") -Force | Out-Null',
        '    Remove-Item -Path (Join-Path $opencodeConfigDir "plugins\\Skill-Insight.ts") -Force -ErrorAction SilentlyContinue',
        '    Remove-Item -Path (Join-Path $opencodeConfigDir "plugins\\Witty-Skill-Insight.ts") -Force -ErrorAction SilentlyContinue',
        '    Remove-Item -Path (Join-Path $homeDir ".opencode\\plugins\\Skill-Insight.ts") -Force -ErrorAction SilentlyContinue',
        '    Remove-Item -Path (Join-Path $homeDir ".opencode\\plugins\\Witty-Skill-Insight.ts") -Force -ErrorAction SilentlyContinue',
        '    Remove-Item -Path (Join-Path $homeDir ".opencode\\plugins\\Witty-Skill-Insight.tui.tsx") -Force -ErrorAction SilentlyContinue',
        '    Invoke-WebRequest -Uri "$AGENT_INSIGHT_BASE_URL/api/setup/opencode" -OutFile (Join-Path $opencodeConfigDir "plugins\\Witty-Skill-Insight.ts")',
        '    Write-Host "⏬ Downloading OpenCode Uploader..."',
        '    Invoke-WebRequest -Uri "$AGENT_INSIGHT_BASE_URL/api/setup/opencode-uploader" -OutFile (Join-Path $homeDir ".agent-insight\\opencode_uploader_client.js")',
        '    Write-Host "⏬ Downloading OpenCode TUI Plugin..."',
        '    $tuiPluginPath = (Join-Path $opencodeConfigDir "plugins\\Witty-Skill-Insight.tui.tsx")',
        '    Invoke-WebRequest -Uri "$AGENT_INSIGHT_BASE_URL/api/setup/opencode-tui" -OutFile $tuiPluginPath',
        '    $tuiConfigFile = (Join-Path $opencodeConfigDir "tui.json")',
        '    try {',
        '        $data = @{}',
        '        if (Test-Path $tuiConfigFile) {',
        '            $raw = Get-Content $tuiConfigFile -Raw',
        '            if ($raw -and $raw.Trim()) { $data = $raw | ConvertFrom-Json }',
        '        }',
        '        if (-not $data.plugin) { $data | Add-Member -MemberType NoteProperty -Name plugin -Value @() -Force }',
        '        if ($data.plugin -notcontains $tuiPluginPath) { $data.plugin += $tuiPluginPath }',
        '        $data | ConvertTo-Json -Depth 10 | Set-Content -Path $tuiConfigFile -Encoding UTF8',
        '    } catch {',
        '        Write-Host "⚠️  Failed to patch tui.json for TUI plugin."',
        '    }',
        '}',
        '',
        'if ($INSTALL_CLAUDE) {',
        '    Write-Host "🛰️  Claude Code will use official OpenTelemetry logs; no session-file watcher is required."',
        '}',
        '',
        'if ($INSTALL_HERMES) {',
        '    Write-Host "Installing Agent Insight Hermes plugin..."',
        '    $hermesHome = if ($env:HERMES_HOME) { $env:HERMES_HOME } else { Join-Path $homeDir ".hermes" }',
        '    $hermesPluginDir = Join-Path $hermesHome "plugins\\agent_insight_hermes"',
        '    New-Item -ItemType Directory -Path $hermesPluginDir -Force | Out-Null',
        '    Invoke-WebRequest -Uri "$AGENT_INSIGHT_BASE_URL/api/setup/hermes-plugin" -OutFile (Join-Path $hermesPluginDir "__init__.py")',
        '    @("name: agent_insight_hermes", "version: 0.2.0", "description: Agent Insight telemetry for Hermes", "provides_hooks:", "  - pre_llm_call", "  - post_llm_call", "  - pre_api_request", "  - post_api_request", "  - api_request_error", "  - pre_tool_call", "  - post_tool_call", "  - subagent_start", "  - subagent_stop", "  - on_session_end") | Set-Content -Path (Join-Path $hermesPluginDir "plugin.yaml") -Encoding UTF8',
        '    $hermesCmd = Get-Command hermes -ErrorAction SilentlyContinue',
        '    if ($hermesCmd) {',
        '        & $hermesCmd.Source plugins enable agent_insight_hermes',
        '    } else {',
        '        Write-Host "Warning: hermes command not found. The plugin files were installed; enable agent_insight_hermes after installing Hermes."',
        '    }',
        '}',
        '',
        'if ($INSTALL_JIUWEN) {',
        '    Write-Host "⏬ Installing Agent-insight JiuwenSwarm extension..."',
        '    $jwHome = if ($env:JIUWENSWARM_DATA_DIR) { $env:JIUWENSWARM_DATA_DIR } else { Join-Path $homeDir ".jiuwenswarm" }',
        '    $jwExtDir = Join-Path $jwHome "extensions\\agent-insight-observability"',
        '    New-Item -ItemType Directory -Path $jwExtDir -Force | Out-Null',
        '    New-Item -ItemType Directory -Path (Join-Path $jwHome "config") -Force | Out-Null',
        '    Invoke-WebRequest -Uri "$AGENT_INSIGHT_BASE_URL/api/setup/jiuwen-extension" -OutFile (Join-Path $jwExtDir "extension.py")',
        '    @(\'id: agent-insight-observability\', \'name: agent-insight-observability\', \'version: 0.1.0\', \'description: Zero-code observability onboarding for JiuwenSwarm via agent-core OTLP.\', \'author: agent-insight\', \'min_jiuwenswarm_version: "0.2.0"\', \'dependencies: {}\', \'config_schema:\', \'  type: object\') | Set-Content -Path (Join-Path $jwExtDir "extension.yaml") -Encoding UTF8',
        '    Write-Host "✅ JiuwenSwarm extension installed at $jwExtDir"',
        '}',
        '',
        'if ($INSTALL_TRAE) {',
        '    Write-Host "Installing Trae IDE collector..."',
        '    $tmpVsix = Join-Path $env:TEMP "trae-collector.vsix"',
        '    Write-Host "  Step 1: Downloading VSIX..."',
        '    (New-Object System.Net.WebClient).DownloadFile("$AGENT_INSIGHT_BASE_URL/api/setup/trae", $tmpVsix)',
        '',
        '    $installed = $false',
        '    # Try TRAE CLI first (check PATH + common install locations)',
        '    $traeCli = Get-Command trae-cn -ErrorAction SilentlyContinue',
        '    if (-not $traeCli) {',
        '        $traeDirs = @("$env:LOCALAPPDATA\\Programs\\trae-cn", "$env:APPDATA\\trae-cn")',
        '        foreach ($d in $traeDirs) {',
        '            $bin = Join-Path $d "bin\\trae-cn.cmd"',
        '            if (Test-Path $bin) { $traeCli = $bin; break }',
        '        }',
        '    }',
        '    if (-not $traeCli) { $traeCli = Get-Command trae -ErrorAction SilentlyContinue }',
        '    if ($traeCli) {',
        '        Write-Host "  Step 2: Installing via CLI..."',
        '        & $traeCli --install-extension $tmpVsix --force',
        '        if ($LASTEXITCODE -eq 0) { $installed = $true }',
        '    }',
        '',
        '    if (-not $installed) {',
        '        Write-Host "  Step 2: No CLI found, deploying to filesystem..."',
        '        # Detect TRAE directory',
        '        $traeRoot = $null',
        '        foreach ($d in @("$homeDir\\.trae-cn", "$homeDir\\.trae-cn-server")) {',
        '            if (Test-Path $d) { $traeRoot = $d; break }',
        '        }',
        '        if (-not $traeRoot) { $traeRoot = "$homeDir\\.trae-cn-server" }',
        '',
        '        $extDir = Join-Path $traeRoot "extensions"',
        '        $extName = "agent-insight.agent-insight-trae-collector-0.1.0"',
        '        $target = Join-Path $extDir $extName',
        '',
        '        Write-Host "  Step 3: Extracting VSIX to $target..."',
        '        if (Test-Path $target) { Remove-Item $target -Recurse -Force }',
        '        Add-Type -AssemblyName System.IO.Compression.FileSystem',
        '        [System.IO.Compression.ZipFile]::ExtractToDirectory($tmpVsix, $target)',
        '        # Move files from extension/ subdirectory to root',
        '        $extSubDir = Join-Path $target "extension"',
        '        if (Test-Path $extSubDir) {',
        '            Get-ChildItem $extSubDir | Copy-Item -Destination $target -Recurse -Force',
        '            Remove-Item $extSubDir -Recurse -Force',
        '            Remove-Item (Join-Path $target "extension.vsixmanifest") -Force -ErrorAction SilentlyContinue',
        '            Remove-Item (Join-Path $target "[Content_Types].xml") -Force -ErrorAction SilentlyContinue',
        '        }',
        '',
        '        # Register in extensions.json',
        '        Write-Host "  Step 4: Registering extension..."',
        '        $extJson = Join-Path $extDir "extensions.json"',
        '        $extId = "agent-insight.agent-insight-trae-collector"',
        '        $ts = [int64]((Get-Date).ToUniversalTime() - (Get-Date "1970-01-01")).TotalMilliseconds',
        '        $normalizedTarget = $target -replace \'\\\\\', \'/\'',
        '        $nodeScript = @\'',
        'const fs = require("fs");',
        'const extJson = process.argv[2];',
        'const fsPath = process.argv[3];',
        'const normPath = process.argv[4];',
        'const extName = process.argv[5];',
        'const extId = process.argv[6];',
        'const ts = parseInt(process.argv[7], 10);',
        'const newEntry = {',
        '    identifier: { id: extId },',
        '    version: "0.1.0",',
        '    location: { "$mid": 1, fsPath: fsPath, path: normPath, scheme: "file" },',
        '    relativeLocation: extName,',
        '    metadata: { isMachineScoped: true, installedTimestamp: ts, pinned: true, source: "vsix" }',
        '};',
        'let raw = "";',
        'if (fs.existsSync(extJson)) {',
        '    let buf = fs.readFileSync(extJson);',
        '    if (buf.length >= 3 && buf[0] === 0xEF && buf[1] === 0xBB && buf[2] === 0xBF) { buf = buf.slice(3); }',
        '    raw = buf.toString("utf8").trim();',
        '}',
        'if (!raw) {',
        '    fs.writeFileSync(extJson, JSON.stringify([newEntry], null, 2));',
        '    console.log("Created new extensions.json");',
        '} else {',
        '    try {',
        '        let data = JSON.parse(raw);',
        '        let exts = Array.isArray(data) ? data : (data && Array.isArray(data.value) ? data.value : [data]);',
        '        exts = exts.filter(e => e && e.identifier && e.identifier.id !== extId);',
        '        exts.push(newEntry);',
        '        fs.writeFileSync(extJson, JSON.stringify(exts, null, 2));',
        '        console.log("Extension registered successfully, total:", exts.length);',
        '    } catch (e) {',
        '        console.error("JSON parse failed, using string append:", e.message);',
        '        if (raw.startsWith("[") && raw.endsWith("]")) {',
        '            const insertPos = raw.lastIndexOf("]");',
        '            const before = raw.slice(0, insertPos).trimEnd();',
        '            const sep = before.length > 0 && before.endsWith("}") ? ",\\n" : "";',
        '            const newContent = before + sep + JSON.stringify(newEntry, null, 2) + "\\n" + raw.slice(insertPos);',
        '            fs.writeFileSync(extJson, newContent);',
        '            console.log("Appended via string mode");',
        '        } else {',
        '            fs.writeFileSync(extJson, JSON.stringify([newEntry], null, 2));',
        '            console.log("Recreated extensions.json");',
        '        }',
        '    }',
        '}',
        '\'@',
        '        $nodeScriptPath = Join-Path $env:TEMP "register-trae-ext.js"',
        '        Set-Content -Path $nodeScriptPath -Value $nodeScript -Encoding UTF8',
        '        node $nodeScriptPath $extJson $target $normalizedTarget $extName $extId $ts',
        '        Remove-Item $nodeScriptPath -Force -ErrorAction SilentlyContinue',
        '        $installed = $true',
        '    }',
        '',
        '    Remove-Item $tmpVsix -Force -ErrorAction SilentlyContinue',
        '',
        '    # Step 5: Deploy Hook scripts via WSL',
        '    Write-Host "  Step 5: Deploying Hook scripts..."',
        '    $setupScript = Join-Path $target "setup.ps1"',
        '    if (Test-Path $setupScript) {',
        '        powershell -ExecutionPolicy Bypass -File $setupScript',
        '    } else {',
        '        Write-Host "  [WARN] setup.ps1 not found"',
        '    }',
        '',
        '    Write-Host "  [OK] Trae IDE collector installed"',
        '    Write-Host "  [NOTE] Restart TRAE IDE to activate"',
        '}',
        '',
        '# 4. Configure ~/.agent-insight/.env',
        '$AGENT_INSIGHT_CONFIG_FILE = "$homeDir\\.agent-insight\\.env"',
        '$EXISTING_KEY = ""',
        '$EXISTING_HOST = ""',
        '$EXISTING_SHOW_TASK_STATS = ""',
        'if (Test-Path $AGENT_INSIGHT_CONFIG_FILE) {',
        '    $content = Get-Content $AGENT_INSIGHT_CONFIG_FILE',
        '    $keyLine = $content | Select-String \'^AGENT_INSIGHT_API_KEY=\' | Select-Object -First 1',
        '    $hostLine = $content | Select-String \'^AGENT_INSIGHT_HOST=\' | Select-Object -First 1',
        '    $showLine = $content | Select-String \'^AGENT_INSIGHT_SHOW_TASK_STATS=\' | Select-Object -First 1',
        '    if ($keyLine) {',
        '        $EXISTING_KEY = $keyLine.Line.Substring(\'AGENT_INSIGHT_API_KEY=\'.Length)',
        '    }',
        '    if ($hostLine) {',
        '        $EXISTING_HOST = $hostLine.Line.Substring(\'AGENT_INSIGHT_HOST=\'.Length)',
        '    }',
        '    if ($showLine) {',
        '        $EXISTING_SHOW_TASK_STATS = $showLine.Line.Substring(\'AGENT_INSIGHT_SHOW_TASK_STATS=\'.Length)',
        '    }',
        '}',
        '',
        '# -- API Key Logic --',
        '$FINAL_KEY = if ($AGENT_INSIGHT_SETUP_API_KEY) { $AGENT_INSIGHT_SETUP_API_KEY } else { $EXISTING_KEY }',
        'if ($AGENT_INSIGHT_SETUP_API_KEY) {',
        '    Write-Host "🔑 Using API Key from setup URL."',
        '} elseif ($EXISTING_KEY) {',
        '    Write-Host "🔑 Found existing API Key."',
        '    $USE_EXISTING = Read-Host "👉 Use existing key? (y/N, Default: y)"',
        '    if ($USE_EXISTING -match \'^[Nn]$\') {',
        '        $FINAL_KEY = Read-Host "👉 Please enter your NEW API Key"',
        '    }',
        '} else {',
        '    Write-Host "🔑 AGENT_INSIGHT_API_KEY is not set."',
        '    $FINAL_KEY = Read-Host "👉 Please enter your API Key"',
        '}',
        '',
        '# -- Host Logic --',
        '$FINAL_HOST = $AGENT_INSIGHT_HOST',
        'if ($EXISTING_HOST -and ($EXISTING_HOST -ne $AGENT_INSIGHT_HOST)) {',
        '    Write-Host "🌐 Current Host in config: $EXISTING_HOST"',
        '    Write-Host "🌐 New Host detected: $AGENT_INSIGHT_HOST"',
        '    $CHANGE_HOST = Read-Host "👉 Change to new Host? (y/N, Default: y)"',
        '    if ($CHANGE_HOST -match \'^[Nn]$\') {',
        '        $FINAL_HOST = $EXISTING_HOST',
        '    }',
        '} elseif (-not $EXISTING_HOST) {',
        '    $FINAL_HOST = $AGENT_INSIGHT_HOST',
        '}',
        '',
        '$FINAL_SHOW_TASK_STATS = $EXISTING_SHOW_TASK_STATS',
        'if (-not $FINAL_SHOW_TASK_STATS) {',
        '    $FINAL_SHOW_TASK_STATS = "true"',
        '}',
        '',
        'if (-not $FINAL_KEY) {',
        '    Write-Host "⚠️  Warning: No API Key provided. Telemetry upload will fail until you set it in $AGENT_INSIGHT_CONFIG_FILE"',
        '}',
        '',
        'Write-Host "⚙️  Updating configuration..."',
        'New-Item -ItemType File -Path $AGENT_INSIGHT_CONFIG_FILE -Force | Out-Null',
        'Copy-Item $AGENT_INSIGHT_CONFIG_FILE "$AGENT_INSIGHT_CONFIG_FILE.bak"',
        '$content = Get-Content "$AGENT_INSIGHT_CONFIG_FILE.bak"',
        '$content | Where-Object { $_ -notmatch \'^AGENT_INSIGHT_HOST=\' -and $_ -notmatch \'^AGENT_INSIGHT_API_KEY=\' -and $_ -notmatch \'^AGENT_INSIGHT_SHOW_TASK_STATS=\' -and $_ -notmatch \'^AGENT_INSIGHT_RETENTION_DAYS=\' -and $_ -notmatch \'^AGENT_INSIGHT_OPENCODE_OTEL_ENABLE=\' -and $_ -notmatch \'^AGENT_INSIGHT_OPENCODE_SPOOL_DIR=\' -and $_ -notmatch \'^AGENT_INSIGHT_OPENCODE_UPLOADER=\' -and $_ -notmatch \'^AGENT_INSIGHT_CLAUDE_OTEL_SPOOL_DIR=\' -and $_ -notmatch \'^AGENT_INSIGHT_CODEAGENT_OTEL_SPOOL_DIR=\' -and $_ -notmatch \'^AGENT_INSIGHT_CLAUDE_OTEL_RAW_API_BODIES=\' -and $_ -notmatch \'^AGENT_INSIGHT_MAX_TOOL_IO=\' -and $_ -notmatch \'^AGENT_INSIGHT_MAX_EVENT_STRING=\' -and $_ -notmatch \'^AGENT_INSIGHT_OPENCODE_UPLOAD_COOLDOWN_MS=\' } | Set-Content $AGENT_INSIGHT_CONFIG_FILE',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_HOST=$FINAL_HOST"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_API_KEY=$FINAL_KEY"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_SHOW_TASK_STATS=$FINAL_SHOW_TASK_STATS"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_RETENTION_DAYS=10"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_OPENCODE_OTEL_ENABLE=true"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_OPENCODE_SPOOL_DIR=$homeDir\\.agent-insight\\otel_data\\opencode"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_OPENCODE_UPLOADER=$homeDir\\.agent-insight\\opencode_uploader_client.js"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_CLAUDE_OTEL_SPOOL_DIR=$homeDir\\.agent-insight\\otel_data\\claude"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_CLAUDE_OTEL_RAW_API_BODIES=file:$homeDir\\.agent-insight\\claude_raw_bodies"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_CODEAGENT_OTEL_SPOOL_DIR=$homeDir\\.agent-insight\\otel_data\\codeagent"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_MAX_TOOL_IO=4000"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_MAX_EVENT_STRING=20000"',
        'Add-Content $AGENT_INSIGHT_CONFIG_FILE "AGENT_INSIGHT_OPENCODE_UPLOAD_COOLDOWN_MS=15000"',
        'Remove-Item "$AGENT_INSIGHT_CONFIG_FILE.bak" -Force',
        'Write-Host "✅ Configuration updated at $AGENT_INSIGHT_CONFIG_FILE"',
        '',
        '# 6.4 Configure Agent Insight Hermes plugin',
        'if ($INSTALL_HERMES) {',
        '    $hermesHome = if ($env:HERMES_HOME) { $env:HERMES_HOME } else { Join-Path $homeDir ".hermes" }',
        '    $hermesPluginDir = Join-Path $hermesHome "plugins\\agent_insight_hermes"',
        '    New-Item -ItemType Directory -Path $hermesPluginDir -Force | Out-Null',
        '    $hermesConfig = @{ host = $FINAL_HOST.TrimEnd("/"); api_key = $FINAL_KEY; service_name = "hermes"; max_content_chars = 200000; spool_dir = (Join-Path $homeDir ".agent-insight\\data\\hermes-otel-spool"); log_file = (Join-Path $homeDir ".agent-insight\\logs\\hermes-plugin.log") } | ConvertTo-Json',
        '    Set-Content -Path (Join-Path $hermesPluginDir "config.json") -Value $hermesConfig -Encoding UTF8',
        '    Write-Host "Agent Insight Hermes config written to $hermesPluginDir\\config.json"',
        '}',
        '',
        '# 6.45 Configure JiuwenSwarm telemetry (workspace config\\.env, read by the extension)',
        'if ($INSTALL_JIUWEN) {',
        '    $jwHome = if ($env:JIUWENSWARM_DATA_DIR) { $env:JIUWENSWARM_DATA_DIR } else { Join-Path $homeDir ".jiuwenswarm" }',
        '    $jwEnv = Join-Path $jwHome "config\\.env"',
        '    $jwExtParent = Join-Path $jwHome "extensions"',
        '    $jwOtlpHost = if ($FINAL_HOST -match "^https?://") { $FINAL_HOST } else { "http://$FINAL_HOST" }',
        '    $jwOtlpEndpoint = $jwOtlpHost.TrimEnd("/") + "/api/ingest/otel/v1/traces"',
        '    New-Item -ItemType Directory -Path (Join-Path $jwHome "config") -Force | Out-Null',
        '    New-Item -ItemType File -Path $jwEnv -Force | Out-Null',
        '    $jwPrev = Get-Content $jwEnv',
        '    $prevExtLine = $jwPrev | Select-String \'^EXTENSION_DIRS=\' | Select-Object -First 1',
        '    $prevExtDirs = if ($prevExtLine) { $prevExtLine.Line.Substring(\'EXTENSION_DIRS=\'.Length).Trim(\'"\').Trim("\'") } else { "jiuwenswarm/extensions" }',
        '    if (-not $prevExtDirs) { $prevExtDirs = "jiuwenswarm/extensions" }',
        '    if ($prevExtDirs.Split(";") -notcontains $jwExtParent) { $newExtDirs = "$prevExtDirs;$jwExtParent" } else { $newExtDirs = $prevExtDirs }',
        '    $jwPrev | Where-Object { $_ -notmatch \'^OTEL_ENABLED=\' -and $_ -notmatch \'^AGENT_INSIGHT_OTLP_ENDPOINT=\' -and $_ -notmatch \'^AGENT_INSIGHT_API_KEY=\' -and $_ -notmatch \'^EXTENSION_DIRS=\' } | Set-Content $jwEnv',
        '    Add-Content $jwEnv "OTEL_ENABLED=true"',
        '    Add-Content $jwEnv "AGENT_INSIGHT_OTLP_ENDPOINT=$jwOtlpEndpoint"',
        '    Add-Content $jwEnv "AGENT_INSIGHT_API_KEY=$FINAL_KEY"',
        '    Add-Content $jwEnv "EXTENSION_DIRS=$newExtDirs"',
        '    Write-Host "✅ JiuwenSwarm telemetry configured -> $jwOtlpEndpoint (service=jiuwenswarm)"',
        '}',
        '',
        '# 6.5 Configure Claude Code official OTel logs',
        'if ($INSTALL_CLAUDE) {',
        '    $claudeOtelScript = @\'',
        'function Invoke-SkillInsightClaude {',
        '  $envFile = Join-Path $env:USERPROFILE ".agent-insight\\.env"',
        '  if (Test-Path $envFile) {',
        '    Get-Content $envFile | ForEach-Object {',
        '      if ($_ -match "^([^#=]+)=(.*)$") { [Environment]::SetEnvironmentVariable($matches[1], $matches[2], "Process") }',
        '    }',
        '  }',
        '  $siHost = if ($env:AGENT_INSIGHT_HOST) { $env:AGENT_INSIGHT_HOST } else { "127.0.0.1:3000" }',
        '  if ($siHost -notmatch "^https?://") { $siHost = "http://$siHost" }',
        '  $siHost = $siHost.TrimEnd("/")',
        '  $env:CLAUDE_CODE_ENABLE_TELEMETRY = "1"',
        '  $env:OTEL_LOGS_EXPORTER = "otlp"',
        '  if (-not $env:OTEL_METRICS_EXPORTER) { $env:OTEL_METRICS_EXPORTER = "none" }',
        '  $env:OTEL_EXPORTER_OTLP_LOGS_PROTOCOL = "http/json"',
        '  $env:OTEL_EXPORTER_OTLP_LOGS_ENDPOINT = "$siHost/api/ingest/otel/v1/logs"',
        '  $env:OTEL_EXPORTER_OTLP_HEADERS = "x-witty-api-key=$($env:AGENT_INSIGHT_API_KEY)"',
        '  $env:OTEL_LOG_USER_PROMPTS = "1"',
        '  $env:OTEL_LOG_TOOL_DETAILS = "1"',
        '  $env:OTEL_LOG_TOOL_CONTENT = "1"',
        '  $rawBodyDir = Join-Path $env:USERPROFILE ".agent-insight\\claude_raw_bodies"',
        '  New-Item -ItemType Directory -Path $rawBodyDir -Force | Out-Null',
        '  if (-not $env:AGENT_INSIGHT_CLAUDE_OTEL_RAW_API_BODIES) { $env:AGENT_INSIGHT_CLAUDE_OTEL_RAW_API_BODIES = "file:$rawBodyDir" }',
        '  $env:OTEL_LOG_RAW_API_BODIES = $env:AGENT_INSIGHT_CLAUDE_OTEL_RAW_API_BODIES',
        '  $cmd = Get-Command claude -CommandType Application -ErrorAction SilentlyContinue',
        '  if (-not $cmd) { throw "claude executable not found in PATH" }',
        '  & $cmd.Source @args',
        '}',
        'Set-Alias claude Invoke-SkillInsightClaude',
        '\'@',
        '    $claudeOtelPath = "$homeDir\\.agent-insight\\claude_otel_env.ps1"',
        '    Set-Content -Path $claudeOtelPath -Value $claudeOtelScript -Encoding UTF8',
        '    $profileDir = Split-Path $PROFILE -Parent',
        '    if ($profileDir) { New-Item -ItemType Directory -Path $profileDir -Force | Out-Null }',
        '    $profileText = if (Test-Path $PROFILE) { Get-Content $PROFILE -Raw } else { "" }',
        '    if (-not ($profileText.Contains(".agent-insight\\claude_otel_env.ps1") -or $profileText.Contains(".agent-insight/claude_otel_env.ps1"))) {',
        '        Add-Content -Path $PROFILE -Value ""',
        '        Add-Content -Path $PROFILE -Value "# Skill-Insight Claude Code OTel"',
        '        Add-Content -Path $PROFILE -Value ". `"$claudeOtelPath`""',
        '    }',
        '    Write-Host "✅ Claude Code OTel env installed at $claudeOtelPath"',
        '    Write-Host "   Restart PowerShell or run: . `"$claudeOtelPath`""',
        '    Get-Process | Where-Object { $_.CommandLine -like "*claude_watcher_client.ts*" } | Stop-Process -Force -ErrorAction SilentlyContinue',
        '    Remove-Item "$homeDir\\.agent-insight\\claude_watcher_client.ts", "$homeDir\\.agent-insight\\start_claude_watcher.ps1", "$homeDir\\.agent-insight\\stop_claude_watcher.ps1", "$homeDir\\.agent-insight\\claude_watcher.pid" -Force -ErrorAction SilentlyContinue',
        '    Write-Host "🧹 Removed legacy Claude session-file watcher if it was installed."',
        '}',
        '',
        '# 6.6 Configure OpenClaw official OTel logs',
        '# 6.6a Configure CodeAgent OpenTelemetry wrapper',
        'if ($INSTALL_CODEAGENT) {',
        '    $codeAgentOtelScript = @\'',
        'function Invoke-AgentInsightCodeAgent {',
        '  $envFile = Join-Path (Join-Path $env:USERPROFILE ".agent-insight") ".env"',
        '  if (Test-Path $envFile) {',
        '    Get-Content $envFile | ForEach-Object {',
        '      if ($_ -match "^([^#=]+)=(.*)$") { [Environment]::SetEnvironmentVariable($matches[1], $matches[2], "Process") }',
        '    }',
        '  }',
        '  $siHost = if ($env:AGENT_INSIGHT_HOST) { $env:AGENT_INSIGHT_HOST } else { "127.0.0.1:3000" }',
        '  if ($siHost -notmatch "^https?://") { $siHost = "http://$siHost" }',
        '  $siHost = $siHost.TrimEnd("/")',
        '  $env:CODEAGENT3_ENABLE_TELEMETRY = "1"',
        '  $env:OTEL_EXPORTER_OTLP_ENDPOINT = "$siHost/api/ingest/otel"',
        '  $env:OTEL_EXPORTER_OTLP_PROTOCOL = "http/json"',
        '  $env:OTEL_EXPORTER_OTLP_LOGS_PROTOCOL = "http/json"',
        '  $env:OTEL_EXPORTER_OTLP_HEADERS = "x-witty-api-key=$($env:AGENT_INSIGHT_API_KEY)"',
        '  $command = Get-Command codeagent -CommandType Application, ExternalScript -ErrorAction SilentlyContinue | Select-Object -First 1',
        '  if (-not $command) { throw "CodeAgent executable not found in PATH." }',
        '  & $command.Source @args',
        '}',
        'Set-Alias codeagent Invoke-AgentInsightCodeAgent',
        '\'@',
        '    $codeAgentOtelPath = "$homeDir\\.agent-insight\\codeagent_otel_env.ps1"',
        '    Set-Content -Path $codeAgentOtelPath -Value $codeAgentOtelScript -Encoding UTF8',
        '    $profileDir = Split-Path $PROFILE -Parent',
        '    if ($profileDir) { New-Item -ItemType Directory -Path $profileDir -Force | Out-Null }',
        '    if (-not (Test-Path $PROFILE) -or -not ((Get-Content $PROFILE -Raw) -match "codeagent_otel_env.ps1")) {',
        '        Add-Content -Path $PROFILE -Value ""',
        '        Add-Content -Path $PROFILE -Value "# Agent-Insight CodeAgent OTel"',
        '        Add-Content -Path $PROFILE -Value ". `"$codeAgentOtelPath`""',
        '    }',
        '    Write-Host "✅ CodeAgent OTel env installed at $codeAgentOtelPath"',
        '    Write-Host "   Restart PowerShell, then run: codeagent"',
        '    Write-Host "   CodeAgent may still send traces/metrics; Agent Insight accepts and discards those signals."',
        '}',
        '',
        'if ($INSTALL_OPENCLAW) {',
        '    $openclawOtelScript = @\'',
        'function Invoke-SkillInsightOpenClaw {',
        '  $envFile = Join-Path (Join-Path $env:USERPROFILE ".agent-insight") ".env"',
        '  if (Test-Path $envFile) {',
        '    Get-Content $envFile | ForEach-Object {',
        '      if ($_ -match "^([^#=]+)=(.*)$") { [Environment]::SetEnvironmentVariable($matches[1], $matches[2], "Process") }',
        '    }',
        '  }',
        '  $siHost = if ($env:AGENT_INSIGHT_HOST) { $env:AGENT_INSIGHT_HOST } else { "127.0.0.1:3000" }',
        '  if ($siHost -notmatch "^https?://") { $siHost = "http://$siHost" }',
        '  $siHost = $siHost.TrimEnd("/")',
        '  $env:CLAW_ENABLE_TELEMETRY = "1"',
        '  $env:OTEL_LOGS_EXPORTER = "otlp"',
        '  if (-not $env:OTEL_METRICS_EXPORTER) { $env:OTEL_METRICS_EXPORTER = "none" }',
        '  $env:OTEL_EXPORTER_OTLP_LOGS_PROTOCOL = "http/json"',
        '  $env:OTEL_EXPORTER_OTLP_LOGS_ENDPOINT = "$siHost/api/ingest/otel/v1/logs"',
        '  $env:OTEL_EXPORTER_OTLP_TRACES_PROTOCOL = "http/json"',
        '  $env:OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = "$siHost/api/ingest/otel/v1/traces"',
        '  $env:OTEL_EXPORTER_OTLP_HEADERS = "x-witty-api-key=$($env:AGENT_INSIGHT_API_KEY)"',
        '  $env:OTEL_LOG_USER_PROMPTS = "1"',
        '  $env:OTEL_LOG_TOOL_DETAILS = "1"',
        '  $env:OTEL_LOG_TOOL_CONTENT = "1"',
        '  $cmd = Get-Command "openclaw" -CommandType Application, ExternalScript -ErrorAction SilentlyContinue | Select-Object -First 1',
        '  if (-not $cmd) { throw "openclaw executable not found in PATH" }',
        '  & $cmd @args',
        '}',
        'Set-Alias openclaw Invoke-SkillInsightOpenClaw',
        '\'@',
        '    $openclawOtelPath = "$homeDir\\.agent-insight\\openclaw_otel_env.ps1"',
        '    Set-Content -Path $openclawOtelPath -Value $openclawOtelScript -Encoding UTF8',
        '    $profileDir = Split-Path $PROFILE -Parent',
        '    if ($profileDir) { New-Item -ItemType Directory -Path $profileDir -Force | Out-Null }',
        '    if (-not (Test-Path $PROFILE) -or -not ((Get-Content $PROFILE -Raw) -match "openclaw_otel_env.ps1")) {',
        '        Add-Content -Path $PROFILE -Value ""',
        '        Add-Content -Path $PROFILE -Value "# Skill-Insight OpenClaw OTel"',
        '        Add-Content -Path $PROFILE -Value ". `"$openclawOtelPath`""',
        '    }',
        '    Write-Host "✅ OpenClaw OTel env installed at $openclawOtelPath"',
        '    Write-Host "   Restart PowerShell or run: . `"$openclawOtelPath`""',
        '    Write-Host ""',
        '    Write-Host "============================================"',
        '    Write-Host "  OpenClaw OTel -- 纯配置方式（复制 env 块）"',
        '    Write-Host "============================================"',
        '    Write-Host ""',
        '    Write-Host "  `$env:CLAW_ENABLE_TELEMETRY = 1"',
        '    Write-Host "  `$env:OTEL_LOGS_EXPORTER = \"otlp\""',
        '    Write-Host "  `$env:OTEL_METRICS_EXPORTER = \"none\""',
        '    Write-Host "  `$env:OTEL_EXPORTER_OTLP_LOGS_PROTOCOL = \"http/protobuf\""',
        '    Write-Host "  `$env:OTEL_EXPORTER_OTLP_LOGS_ENDPOINT = \"http://127.0.0.1:3000/api/ingest/otel/v1/traces\""',
        '    Write-Host "  `$env:OTEL_EXPORTER_OTLP_TRACES_PROTOCOL = \"http/protobuf\""',
        '    Write-Host "  `$env:OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = \"http://127.0.0.1:3000/api/ingest/otel/v1/traces\""',
        '    Write-Host "  `$env:OTEL_EXPORTER_OTLP_HEADERS = \"x-witty-api-key=<your-api-key>\""',
        '    Write-Host "  `$env:OTEL_SERVICE_NAME = \"openclaw\""',
        '    Write-Host ""',
        '    Write-Host "---"',
        '    Write-Host "!! OTel 纯配置方式 与 Watcher 模式互斥。"',
        '    Write-Host "   选择一种方式即可，不要同时启用两种。"',
        '    Write-Host "   如已启用 watcher，请移除以上 OTel 环境变量避免重复。"',
        '    Write-Host ""',
        '}',
        '',
        '# 7. Create Watcher Startup/Stop Scripts',
        '$NEEDS_WATCHER_SCRIPTS = $false',
        'if ($INSTALL_OPENCODE) {',
        '    $NEEDS_WATCHER_SCRIPTS = $true',
        '}',
        '',
        'if ($NEEDS_WATCHER_SCRIPTS) {',
        '    Write-Host ""',
        '    Write-Host "📝 Creating watcher management scripts..."',
        '',
        // OpenCode uploader fallback daemon (PowerShell). Polls every N seconds;
        // mtime gate inside the uploader keeps idle cycles ~5ms.
        '    if ($INSTALL_OPENCODE) {',
        '        $startScript = @\'',
        'Get-Process | Where-Object { $_.CommandLine -like "*opencode_uploader_client.js*" } | Stop-Process -Force -ErrorAction SilentlyContinue',
        'Get-Process | Where-Object { $_.CommandLine -like "*skill-insight-opencode-uploader-loop*" } | Stop-Process -Force -ErrorAction SilentlyContinue',
        'New-Item -ItemType Directory -Path "$env:USERPROFILE\\.agent-insight\\logs" -Force | Out-Null',
        '$intervalSec = if ($env:AGENT_INSIGHT_OPENCODE_UPLOADER_INTERVAL_SEC) { $env:AGENT_INSIGHT_OPENCODE_UPLOADER_INTERVAL_SEC } else { "300" }',
        '$logFile = "$env:USERPROFILE\\.agent-insight\\logs\\opencode_uploader.log"',
        '$uploaderPath = "$env:USERPROFILE\\.agent-insight\\opencode_uploader_client.js"',
        '$runtime = if (Get-Command node -ErrorAction SilentlyContinue) { "node" } elseif (Get-Command bun -ErrorAction SilentlyContinue) { "bun" } else { $null }',
        'if (-not $runtime) {',
        '    Add-Content $logFile "[$(Get-Date)] Skipped: node/bun not installed"',
        '    return',
        '}',
        '# Sentinel marker in script body so it can be matched by CommandLine search.',
        '$loopBody = @"',
        '# skill-insight-opencode-uploader-loop',
        'while (`$true) {',
        '    & `"$runtime`" `"$uploaderPath`" *>> `"$logFile`"',
        '    Start-Sleep -Seconds $intervalSec',
        '}',
        '"@',
        '$proc = Start-Process -FilePath "powershell" -ArgumentList "-NoProfile", "-Command", $loopBody -PassThru -WindowStyle Hidden',
        'Set-Content "$env:USERPROFILE\\.agent-insight\\opencode_uploader.pid" $proc.Id',
        'Write-Host "OpenCode uploader daemon started with PID $($proc.Id) (interval=${intervalSec}s)"',
        '\'@',
        '        Set-Content -Path "$homeDir\\.agent-insight\\start_opencode_uploader.ps1" -Value $startScript -Encoding UTF8',
        '',
        '        $stopScript = @\'',
        'Get-Process | Where-Object { $_.CommandLine -like "*skill-insight-opencode-uploader-loop*" } | Stop-Process -Force -ErrorAction SilentlyContinue',
        'Get-Process | Where-Object { $_.CommandLine -like "*opencode_uploader_client.js*" } | Stop-Process -Force -ErrorAction SilentlyContinue',
        'Remove-Item "$env:USERPROFILE\\.agent-insight\\opencode_uploader.pid" -Force -ErrorAction SilentlyContinue',
        'Write-Host "OpenCode uploader daemon stopped"',
        '\'@',
        '        Set-Content -Path "$homeDir\\.agent-insight\\stop_opencode_uploader.ps1" -Value $stopScript -Encoding UTF8',
        '    }',
        '',
        '    $combinedStart = \'Write-Host "Starting Agent-Insight watchers..."\'',
        '    if ($INSTALL_OPENCODE) { $combinedStart += [char]10 + "& `"$homeDir\\.agent-insight\\start_opencode_uploader.ps1`"" }',
        '    $combinedStart += [char]10 + \'Write-Host "All watchers started!"\'',
        '    Set-Content -Path "$homeDir\\.agent-insight\\start_watchers.ps1" -Value $combinedStart -Encoding UTF8',
        '',
        '    $combinedStop = \'Write-Host "Stopping Agent-Insight watchers..."\'',
        '    if ($INSTALL_OPENCODE) { $combinedStop += [char]10 + "& `"$homeDir\\.agent-insight\\stop_opencode_uploader.ps1`"" }',
        '    $combinedStop += [char]10 + \'Write-Host "All watchers stopped!"\'',
        '    Set-Content -Path "$homeDir\\.agent-insight\\stop_watchers.ps1" -Value $combinedStop -Encoding UTF8',
        '}',
        '',
        '# 8. Start Watchers Now',
        'if ($NEEDS_WATCHER_SCRIPTS) {',
        '    Write-Host ""',
        '    Write-Host "🚀 Starting telemetry watchers..."',
        '    if (Get-Command npx -ErrorAction SilentlyContinue) {',
        '        & "$homeDir\\.agent-insight\\start_watchers.ps1"',
        '    } else {',
        '        Write-Host "⚠️  Node.js (npx) not found. Skipping watcher startup."',
        '    }',
        '}',
        '',
        '# 10. Final Summary',
        'Write-Host ""',
        'Write-Host "🌟 Agent-Insight Telemetry: READY"',
        'Write-Host "------------------------------------------------"',
        'Write-Host "Installed Components:"',
        'if ($INSTALL_OPENCODE) { Write-Host "  ✅ OpenCode Plugin: $opencodeConfigDir\\plugins\\Witty-Skill-Insight.ts" }',
        'if ($INSTALL_OPENCODE) { Write-Host "  ✅ OpenCode Uploader Daemon: ~/.agent-insight/opencode_uploader_client.js (5-min poll)" }',
        'if ($INSTALL_CLAUDE) { Write-Host "  ✅ Claude Code OTel: ~/.agent-insight/claude_otel_env.ps1" }',
        'if ($INSTALL_CODEAGENT) { Write-Host "  ✅ CodeAgent OTel: ~/.agent-insight/codeagent_otel_env.ps1" }',
        'if ($INSTALL_OPENCLAW) { Write-Host "  ✅ OpenClaw OTel: ~/.agent-insight/openclaw_otel_env.ps1" }',
        'if ($INSTALL_HERMES) { $summaryHermesHome = if ($env:HERMES_HOME) { $env:HERMES_HOME } else { Join-Path $homeDir ".hermes" }; Write-Host "  ✅ Agent Insight Hermes Plugin: $summaryHermesHome\\plugins\\agent_insight_hermes\\config.json" }',
        'if ($INSTALL_JIUWEN) { $summaryJwHome = if ($env:JIUWENSWARM_DATA_DIR) { $env:JIUWENSWARM_DATA_DIR } else { Join-Path $homeDir ".jiuwenswarm" }; Write-Host "  ✅ JiuwenSwarm Extension: $summaryJwHome\\extensions\\agent-insight-observability (telemetry in config\\.env)" }',
        'if (\$INSTALL_TRAE) { Write-Host "  [OK] Trae IDE Collector: ~/.trae-cn-server/extensions/agent-insight.agent-insight-trae-collector-0.1.0" }',
        '',
        'if ($NEEDS_WATCHER_SCRIPTS) {',
        '    Write-Host ""',
        '    Write-Host "Watcher Management:"',
        '    Write-Host "  Start all:    ~/.agent-insight/start_watchers.ps1"',
        '    Write-Host "  Stop all:     ~/.agent-insight/stop_watchers.ps1"',
        '    Write-Host "  Logs:         ~/.agent-insight/logs/"',
        '}',
        '',
        'Write-Host ""',
        'Write-Host "Usage:"',
        'if ($INSTALL_OPENCODE) { Write-Host "  1. Run: opencode run \'hello\'" }',
        'if ($INSTALL_CLAUDE) { Write-Host "  2. Restart PowerShell, then run: claude" }',
        'if ($INSTALL_HERMES) { Write-Host "  3. Restart Hermes or start a new Hermes conversation" }',
        'if ($INSTALL_OPENCLAW) { Write-Host "  4. Restart PowerShell, then run: openclaw" }',
        'if ($INSTALL_CODEAGENT) { Write-Host "  5. Restart PowerShell, then run: codeagent" }',
        'if ($INSTALL_JIUWEN) { Write-Host "  6. Restart JiuwenSwarm (agentserver), then start a conversation" }',
        'if (\$INSTALL_TRAE) { Write-Host "  7. Restart TRAE IDE to activate the collector" }',
        'Write-Host "------------------------------------------------"',
    ];
    return lines.join('\n');
}

export async function GET(request: Request) {
    const host = request.headers.get('x-forwarded-host') || request.headers.get('host') || '127.0.0.1:3000';
    const protocol = request.headers.get('x-forwarded-proto') || 'https';

    const requestUrl = new URL(request.url);
    // --- 直接读取环境变量，不再通过 pathname 截取 ---
    const urlPrefix = process.env.NEXT_PUBLIC_URL_PREFIX || '';
    const baseUrl = `${protocol}://${host}${urlPrefix}`;
    const skillInsightHost = baseUrl;
    const apiKey = requestUrl.searchParams.get('key') || requestUrl.searchParams.get('apiKey') || '';
    // ?frameworks=opencode,claude —— 安装页勾选后带上，脚本据此跳过终端内的交互选择。
    // 不传（老命令）时行为不变，仍在终端里问一遍。
    const preselected = parseFrameworks(requestUrl.searchParams.get('frameworks'));

    const platform = detectPlatform(request);

    if (platform === 'windows') {
        const script = generatePowerShellScript(skillInsightHost, baseUrl, apiKey, preselected);
        return new NextResponse(script, {
            headers: {
                'Content-Type': 'text/plain; charset=utf-8',
            },
        });
    } else {
        const script = generateBashScript(skillInsightHost, baseUrl, apiKey, preselected);
        return new NextResponse(script, {
            headers: {
                'Content-Type': 'text/x-shellscript',
            },
        });
    }
}
