import packageMetadata from "../../../package.json"

export function getAgentInsightClientPackageSpec(): string {
  const override = process.env.AGENT_INSIGHT_CLIENT_PACKAGE_SPEC?.trim()
  if (override) return override
  return `${packageMetadata.name}@${packageMetadata.version}`
}

export function getAgentInsightRasBashInstaller(): string {
  return [
    "install_agent_insight_ras() {",
    '    local ras_host="$1"',
    '    local ras_api_key="$2"',
    '    local ras_tmp=""',
    '    local ras_tarball_name=""',
    '    local ras_attempt=""',
    "",
    '    if [ "${AGENT_INSIGHT_RAS:-1}" = "0" ]; then',
    '        echo "ℹ️  Agent RAS [disabled]: AGENT_INSIGHT_RAS=0"',
    "        return 0",
    "    fi",
    '    if ! command -v npm >/dev/null 2>&1 || ! command -v tar >/dev/null 2>&1; then',
    '        echo "❌ Agent RAS [failed]: npm and tar are required"',
    "        return 1",
    "    fi",
    "",
    '    ras_tmp=$(mktemp -d "${TMPDIR:-/tmp}/agent-insight-ras.XXXXXX") || {',
    '        echo "❌ Agent RAS [failed]: unable to create a temporary directory"',
    "        return 1",
    "    }",
    "",
    "    for ras_attempt in 1 2 3; do",
    '        mkdir -p "$ras_tmp/npm-cache-$ras_attempt"',
    '        if ras_tarball_name=$(NPM_CONFIG_CACHE="$ras_tmp/npm-cache-$ras_attempt" npm pack --ignore-scripts --pack-destination "$ras_tmp" "$AGENT_INSIGHT_PACKAGE_SPEC" 2>"$ras_tmp/npm-pack-$ras_attempt.log" | tail -n 1); then',
    "            break",
    "        fi",
    '        echo "⚠️  Agent RAS package download attempt $ras_attempt/3 failed"',
    '        tail -n 20 "$ras_tmp/npm-pack-$ras_attempt.log" 2>/dev/null || true',
    '        ras_tarball_name=""',
    "    done",
    "",
    '    if [ -z "$ras_tarball_name" ] || [ ! -f "$ras_tmp/$ras_tarball_name" ]; then',
    '        echo "❌ Agent RAS [failed]: unable to download $AGENT_INSIGHT_PACKAGE_SPEC"',
    '        rm -rf -- "$ras_tmp"',
    "        return 1",
    "    fi",
    "",
    '    mkdir -p "$ras_tmp/extracted"',
    '    if ! tar -xzf "$ras_tmp/$ras_tarball_name" -C "$ras_tmp/extracted"; then',
    '        echo "❌ Agent RAS [failed]: unable to extract package tarball"',
    '        rm -rf -- "$ras_tmp"',
    "        return 1",
    "    fi",
    "",
    '    if [ ! -f "$ras_tmp/extracted/package/scripts/install-ras.js" ] || [ ! -f "$ras_tmp/extracted/package/agent_ras/pyproject.toml" ]; then',
    '        echo "❌ Agent RAS [failed]: $AGENT_INSIGHT_PACKAGE_SPEC does not contain the RAS installer/runtime"',
    '        rm -rf -- "$ras_tmp"',
    "        return 1",
    "    fi",
    "",
    '    AGENT_INSIGHT_HOST="$ras_host" AGENT_INSIGHT_API_KEY="$ras_api_key" node "$ras_tmp/extracted/package/scripts/install-ras.js"',
    "    local ras_status=$?",
    '    if [ "$ras_status" -eq 0 ] && [ -n "$ras_host" ] && [ -n "$ras_api_key" ]; then',
    '        local ras_events_url="$ras_host"',
    '        case "$ras_events_url" in http://*|https://*) ;; *) ras_events_url="http://$ras_events_url" ;; esac',
    '        ras_events_url="${ras_events_url%/}/api/ingest/ras-events?taskId=__agent_insight_ras_preflight__"',
    '        if curl -sSf --max-time 60 -H "x-witty-api-key: $ras_api_key" "$ras_events_url" >/dev/null; then',
    '            echo "✅ Agent RAS ingest preflight ready"',
    "        else",
    '            echo "⚠️  Agent RAS ingest preflight failed; runtime installation remains available"',
    "        fi",
    "    fi",
    '    rm -rf -- "$ras_tmp"',
    "    return $ras_status",
    "}",
  ].join("\n")
}

export function getAgentInsightBashDownloadHelper(): string {
  return [
    "download_agent_insight_component() {",
    '    local component_url="$1"',
    '    local component_target="$2"',
    '    local component_label="$3"',
    '    local component_tmp="${component_target}.tmp.$$"',
    "",
    '    mkdir -p "$(dirname "$component_target")"',
    '    if curl -sSf "$component_url" -o "$component_tmp"; then',
    '        mv -f "$component_tmp" "$component_target"',
    '        echo "✅ $component_label ready"',
    "        return 0",
    "    fi",
    '    rm -f -- "$component_tmp"',
    '    echo "❌ Failed to download $component_label from $component_url"',
    "    return 1",
    "}",
  ].join("\n")
}
